version: "3.9"
services:
  composer:
    build:
      context: .
    image: composer
    env_file:
      - .env
    environment:
      - PRODUCTION=1
    ports:
      - "8000:8000"
    depends_on:
      - composer-db
    volumes:
      - composer-data:/usr/src/app/persistent 
  composer-db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - composer-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}

volumes:
  composer-db-data:
  composer-data:
