version: "3.9"
services:
  composer-db:
    image: postgres:13
    restart: "on-failure"
    volumes:
      - composer-db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    env_file:
      - .env

volumes:
  composer-db-data:
  composer-data:
