version: "3.9"
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
      - COMPOSER=composer:latest
    restart: "on-failure"
    ports:
      - "8000:80" # change the 8000 to whatever port you want to use
    volumes:
      - composer-data:/usr/share/nginx/html/media
    depends_on:
      - composer
  composer:
    build:
      context: .
    restart: "on-failure"
    image: composer
    env_file:
      - .env
    depends_on:
      - composer-db
    volumes:
      - composer-data:/usr/src/app/persistent
  composer-db:
    image: postgres:13
    restart: "on-failure"
    volumes:
      - composer-db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  composer-db-data:
  composer-data:
