apiVersion: v1
kind: Pod
metadata:
  name: pg-resetwal
  namespace: composer
spec:
  restartPolicy: Never
  containers:
    - name: fixer
      image: postgres:13
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /data/db
          name: composer-db
  volumes:
    - name: composer-db
      persistentVolumeClaim:
        claimName: composer-db
