//IMPORTS:
const selectors = require('./selectors');
const puppeteer = require("puppeteer");

// INFO
const USERNAME = process.env.TEST_USERNAME 
const PASSWORD = process.env.TEST_PASSWORD 
const baseURL = 'https://composer.sckan.dev.metacell.us/'



//FUNCTIONS AND CONSTANTS

function getTimestamp() {
    const now = new Date();
    const day = now.getDate();
    const month = now.toLocaleString('default', { month: 'short' });
    const year = now.getFullYear();
    const hours = now.getHours();
    // const minutes = now.getMinutes();
    // const seconds = now.getSeconds();
    const formattedDate = `${day}${month}${year}_${hours}h`;
    return formattedDate
}

const maxPmidNumber = 99999999;
const randomPmid = Math.floor(Math.random() * maxPmidNumber) + 1;

const maxPmcidNumber = 999999999;
const randomPmcid = Math.floor(Math.random() * maxPmcidNumber) + 1;

const prefix = "10.";
const maxDoiLength = 16;
const characters = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

let doi = prefix;
while (doi.length < maxDoiLength) {
    const randomIndex = Math.floor(Math.random() * characters.length);
    doi += characters[randomIndex];
}

const currentTime = getTimestamp()

const article_title = `Automated Testing Article - ${currentTime}`
const sentence = `QA - ${currentTime} - Sentence generated by Automated Testing`
const knowledge_statement_1 = `QA_KS_1 - ${currentTime}`
const provenances_1 = 'https://doi.org/google.com'
const species_1 = 'homo sapiens'
const apinatomy_model_name_1 = 'PTcell'
const additional_info_1 = 'Additional Information for KS 1'
const tags = 'Important'
const note = 'Statement List - Distillation - Note'
const path_builder_origin_ = 'abducens motor nuclei'
const path_builder_axon = 'AXON'
const path_builder_via = '10n'
const path_builder_destination = 'adrenal cortex'
const path_builder_axon_terminal = 'AXON-T'



//TESTS:

jest.setTimeout(60000 * 2);
let page;
let browser;


describe('End to End Tests', () => {

    beforeAll(async () => {

        browser = await puppeteer.launch({
            args: [
                '--no-sandbox', '--disable-setuid-sandbox', '--bail',
            ],
            // headless: 'new',
            headless: false,
            defaultViewport: {
                width: 1600,
                height: 1000,
            },
            // slowMo: 30
        });


        page = await browser.newPage();
        await console.log(
            "Checking page",
            baseURL
        );
        await console.log('Starting tests ...')

        await page.goto(baseURL, { waitUntil: 'domcontentloaded' })
        const pageTitle = await page.title();
        console.log(pageTitle);
        expect(pageTitle).toBe('SCKAN Composer')
    });

    afterAll(async () => {

        await browser.close()
    })

    describe('Login Flow', () => {

        // (shouldSkipLoginTest ? it.skip : it)('HomePage', async () => {
        it('Home Page', async () => {
            console.log('Homepage')
            await page.waitForSelector(selectors.LOGIN_PAGE, { timeout: 60000 })
            await page.waitForSelector(selectors.COOKIE_MODAL, { timeout: 60000 })
            await page.waitForSelector(selectors.ACCEPT_COOKIES, { timeout: 60000 })
            await page.click(selectors.ACCEPT_COOKIES)
            await page.waitForSelector(selectors.ACCEPT_COOKIES, { hidden: true });
            console.log('Cookies accepted')

        });

        // (shouldSkipLoginTest ? it.skip : it)('Login', async () => {
        it('Login', async () => {
            console.log('Logging in ...');
            console.log('Testing user: ' + USERNAME)
    
            await page.waitForSelector(selectors.USERNAME, { hidden: false});
            await page.waitForTimeout(1000)
            await page.type(selectors.USERNAME, USERNAME);
            await page.type(selectors.PASSWORD, PASSWORD);
            await page.waitForSelector(selectors.SIGN_IN_BUTTON, { hidden: false });
            await page.click(selectors.SIGN_IN_BUTTON);
            await page.waitForSelector(selectors.SEARCH_ICON, { hidden: false });
            await page.waitForSelector('.MuiDataGrid-row.MuiDataGrid-row--dynamicHeight')
    
            console.log('Logged In');
        });
    })

    describe('Statements List', () => {

        it('Search for the Knowledge Statement in the Statements List page', async () => {
            console.log('Searching for the created Knowledge Statement ...')
            await page.waitForTimeout(3000)
            await page.waitForSelector('li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters')
            const sidebar_buttons = await page.$$('ul.MuiList-root.MuiList-padding > li')
            await sidebar_buttons[1].click()
            await page.waitForSelector(selectors.SEARCH_ICON)
            await page.waitForSelector(selectors.SEARCH_FOR_KS, {hidden:false})
            await page.click(selectors.SEARCH_FOR_KS)
            await page.waitForTimeout(3000)
            await page.type(selectors.SEARCH_FOR_KS, `${knowledge_statement_1}`)
            await page.waitForTimeout(100)
            await page.waitForSelector('.MuiDataGrid-row.MuiDataGrid-row--dynamicHeight')
            await page.waitForTimeout(6000)
            const searched_records_count = await page.$$eval('.MuiDataGrid-row.MuiDataGrid-row--dynamicHeight', elements => elements.length);
            expect(searched_records_count).not.toBeNull()

            await page.waitForSelector(selectors.TABLE_ROW)
            await page.click(selectors.TABLE_ROW)

            await page.waitForSelector(selectors.SENTENCE_PAGE)
            const sentence_status = await page.$$eval('span.MuiChip-label.MuiChip-labelSmall', status => {
                return status.map(status => status.innerText.toLowerCase())
            })
            expect(sentence_status).toContain("compose now")

            console.log('Statement found')
        })

        it('Go to proofing section', async () => {
            console.log('Going to Proofing section ...')
            await page.waitForSelector('button[role="tab"][aria-selected="false"]')
            await page.click('button[role="tab"][aria-selected="false"]')
            await page.waitForTimeout(3000)
            await page.waitForSelector(selectors.ADD_BUTTON_PATH_BUILDER)
            console.log('Proofing section reached')
        })

        it('Add via elements to path builder', async () => {

            console.log('Adding elements to path builder ...')
           
            //Add a Via element
            await page.waitForSelector(selectors.ADD_BUTTON_PATH_BUILDER)
            const add_button = await page.$$('button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textInfo.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-root.MuiButton-text.MuiButton-textInfo.MuiButton-sizeMedium.MuiButton-textSizeMedium')
            await add_button[0].click()
            await page.waitForSelector(selectors.PROGRESS_LOADER, { timeout: 5000, hidden: false });
            await page.waitForSelector(selectors.PROGRESS_LOADER, { hidden: true });
            await page.waitForSelector(selectors.ADDED_ELEMENT)
            const added_via = await page.$$eval('div.MuiSelect-select.MuiSelect-standard.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputAdornedStart', elements => elements.length);
            expect(added_via).toBe(1)

        })

        it('Add destination element to path builder', async () => {

            //Add a Destination element
            await page.waitForSelector(selectors.ADD_BUTTON_PATH_BUILDER, {hidden:false})
            const add_destination_button = await page.$$('button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textInfo.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-root.MuiButton-text.MuiButton-textInfo.MuiButton-sizeMedium.MuiButton-textSizeMedium')
            await add_destination_button[1].click()
            await page.waitForSelector(selectors.PROGRESS_LOADER, { timeout: 5000, hidden: false });
            await page.waitForSelector(selectors.PROGRESS_LOADER, { hidden: true });
            await page.waitForSelector(selectors.ADDED_ELEMENT)
            const added_destination = await page.$$eval('div.MuiSelect-select.MuiSelect-standard.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputAdornedStart', elements => elements.length);
            expect(added_destination).toBe(2)

            console.log('Elements added')
        })

        it('Add Origin', async () => {
            console.log('Adding Origin ...')

            //Origin 
            await page.waitForSelector(selectors.ORIGIN_FIELD)
            await page.click(selectors.ORIGIN_FIELD)
            await page.waitForSelector(selectors.SEARCH_ORIGINS)
            await page.waitForSelector(selectors.CHECKBOX_ITEM)
            await page.waitForTimeout(3000)
            const all_origins = await page.$$eval('.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium', elements => elements.length);
            expect(all_origins).toBeGreaterThan(1)
            await page.click(selectors.SEARCH_ORIGINS)
            await page.click('#simple-popper ul li')

            await page.waitForSelector(selectors.PROGRESS_LOADER, { timeout: 5000, hidden: false });
            await page.waitForSelector(selectors.PROGRESS_LOADER, { hidden: true });
            await page.waitForTimeout(3000)
            await page.waitForSelector(selectors.BIOTECH_ICON_SELECTOR)
            await page.click(selectors.BIOTECH_ICON_SELECTOR)

            // await page.click(selectors.ORIGIN_FIELD)
            await page.waitForTimeout(3000)
            const added_origin = await page.$$eval('form[class="origins"] > div > div  > div  > div  > div  > div  > div > span > div ', status => {
                return status.map(status => status.innerText)
            })
            expect(added_origin).not.toHaveLength(0)
           
            console.log('Origin added')
        })

        it('Add Vias', async () => {

            console.log('Adding Vias ...')
            await page.waitForTimeout(3000)

            //Vias
            await page.waitForSelector(selectors.VIAS_FROM_FIELD)
            await page.click(selectors.VIAS_FROM_FIELD)
            await page.waitForSelector('div:has(> input[placeholder="Search for connections"]')
            await page.waitForSelector(selectors.CHECKBOX_ITEM)
            await page.click('div:has(> input[placeholder="Search for connections"]')
            await page.click('#simple-popper ul li')
            await page.waitForTimeout(1000)
            await page.click('#simple-popper ul li')
            // await page.waitForSelector(selectors.PROGRESS_LOADER, { timeout: 5000, hidden: false });
            // await page.waitForSelector(selectors.PROGRESS_LOADER, { hidden: true });
            await page.waitForTimeout(3000)
            await page.waitForSelector(selectors.BIOTECH_ICON_SELECTOR)
            await page.click(selectors.BIOTECH_ICON_SELECTOR)
            await page.waitForTimeout(3000)

            const added_via_from_field = await page.$$eval('form[class="vias"] > div > div > div > div > div > div > tr > td.MuiTableCell-root.MuiTableCell-sizeMedium.inLineForm:nth-child(2) > div > div > div > div:nth-child(4) > div > div > div > span > div', status => {
                return status.map(status => status.innerText);
            });
            expect(added_via_from_field).not.toHaveLength(0)

            await page.waitForSelector(selectors.VIAS_FIELD)
            await page.click(selectors.VIAS_FIELD)
            await page.waitForSelector(selectors.SEARCH_FOR_VIAS)
            await page.waitForSelector(selectors.CHECKBOX_ITEM)
            await page.waitForTimeout(3000)
            const all_vias = await page.$$eval('.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium', elements => elements.length);
            expect(all_vias).toBeGreaterThan(1)
            await page.click(selectors.SEARCH_FOR_VIAS)
            await page.click('#simple-popper ul li')
            // await page.type(selectors.SEARCH_FOR_VIAS, path_builder_via)
            await page.waitForSelector(selectors.PROGRESS_LOADER, { timeout: 5000, hidden: false });
            await page.waitForSelector(selectors.PROGRESS_LOADER, { hidden: true });
            await page.waitForTimeout(3000)

            await page.waitForSelector(selectors.BIOTECH_ICON_SELECTOR)
            await page.click(selectors.BIOTECH_ICON_SELECTOR)
            await page.waitForTimeout(3000)
            const added_via = await page.$$eval('form[class="vias"] > div > div > div > div > div > div > tr > td.MuiTableCell-root.MuiTableCell-sizeMedium.inLineForm:nth-child(2) > div > div > div > div:nth-child(3) > div > div > div > span > div', status => {
                return status.map(status => status.innerText)
            })
            expect(added_via).not.toHaveLength(0)
            console.log('Via added')

        })

        it('Add Destination', async () => {

            console.log('Adding Destination ...')
            await page.waitForTimeout(3000)

            //Destination
            await page.waitForSelector(selectors.DESTINATION_FROM_FIELD)
            await page.click(selectors.DESTINATION_FROM_FIELD)
            await page.waitForSelector(selectors.SEARCH_FOR_DESTINATIONS)
            await page.click(selectors.SEARCH_FOR_DESTINATIONS)
            await page.waitForSelector(selectors.CHECKBOX_ITEM)
            await page.waitForSelector('#simple-popper ul li', {hidden:false})
            await page.click('#simple-popper ul li')
            await page.waitForTimeout(1000)
            await page.waitForSelector('#simple-popper ul li', {hidden:false})
            await page.click('#simple-popper ul li')
            await page.waitForSelector(selectors.PROGRESS_LOADER, { timeout: 5000, hidden: false });
            await page.waitForSelector(selectors.PROGRESS_LOADER, { hidden: true });
            await page.waitForTimeout(3000)
           
            const added_destination_from_field = await page.$$eval('form[class="destinations"] > div > div > div > div > div > div > tr > td.MuiTableCell-root.MuiTableCell-sizeMedium.inLineForm:nth-child(1) > div > div > div > div:nth-child(3) > div > div > div > span > div', status => {
                return status.map(status => status.innerText);
            });

            expect(added_destination_from_field).not.toHaveLength(0)

            await page.waitForSelector(selectors.FROM_FIELD)
            await page.click(selectors.FROM_FIELD)
            await page.waitForSelector(selectors.SEARCH_FOR_DESTINATIONS)
            await page.waitForSelector(selectors.CHECKBOX_ITEM)
            await page.waitForTimeout(3000)
            const all_destinations = await page.$$eval('.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium', elements => elements.length);
            expect(all_destinations).toBeGreaterThan(1)
            await page.click(selectors.SEARCH_FOR_DESTINATIONS)
            await page.waitForSelector(selectors.CHECKBOX_ITEM)
            await page.waitForSelector('#simple-popper ul li', {hidden:false})
            await page.click('#simple-popper ul li')
            await page.waitForTimeout(1000)
           
            await page.waitForSelector(selectors.PROGRESS_LOADER, { timeout: 5000, hidden: false });
            await page.waitForSelector(selectors.PROGRESS_LOADER, { hidden: true });
            await page.waitForTimeout(3000)
           
            const added_destination = await page.$$eval('form[class="destinations"] > div > div > div > div > div > div > tr > td > div > div > div > div:nth-child(2) > div > div > div > span > div', status => {
                return status.map(status => status.innerText)
            })
            expect(added_destination).not.toHaveLength(0)

            console.log('Destination added')
        })

        it('Add Forward Connection', async () => {
            console.log('Adding Forward Connection ...')
            page.on('dialog', async dialog => {
                await dialog.accept();
            });
            await page.waitForSelector('.form-group.field.field-string > div > div > span > div')
            await page.click('.form-group.field.field-string > div > div > span > div')
            await page.waitForSelector('#simple-popper ul li', {hidden:false})
            await page.click('#simple-popper ul li')
            await page.waitForTimeout(3000)
            const forward_connection_element = await page.$('.form-group.field.field-string > div > div > span > div');
            const fctextContent = await page.evaluate(el => el.textContent, forward_connection_element);
            expect(fctextContent).not.toBe('');
            console.log('Forward Connection added')
        })


        it('Check Statement Preview', async () => {
            console.log('Checking Statement Preview ...')
            await page.waitForTimeout(3000)
            const h5divs = await page.$$('div.MuiStack-root:has(h5.MuiTypography-root.MuiTypography-h5)');
            const thirdDivTextContent = await page.evaluate(div => div.innerText, h5divs[2]);
            expect(thirdDivTextContent.length).toBeGreaterThan(8);

            console.log('Statement Preview filled')
        })

        it.skip('Reset Population Diagram', async () => {
            console.log('Reseting Population Diagram ...')
            await page.waitForTimeout(1000)
            await page.waitForSelector('button[aria-label="Reset to default visualisation"]', {hidden:false})
            await page.click('button[aria-label="Reset to default visualisation"]')
            await page.waitForSelector('.MuiDialogActions-root.MuiDialogActions-spacing', {hidden:false})
            const buttons = await page.$$('.MuiDialogActions-root.MuiDialogActions-spacing button');
            await buttons[1].click();
            await page.waitForTimeout(3000)
            console.log('Population Diagram reset')
        })

        it('Check Population Diagram', async () => {
            console.log('Checking Population Diagram ...')

            await page.waitForTimeout(1000)
            await page.waitForSelector('button[aria-label="Reset to default visualisation"]', {hidden:false})
            await page.waitForSelector('div.node', {hidden:false})
            const nodes = await page.$$('div.node');
            //expect(nodes.length).toBe(3);
            expect(nodes.length).toBeGreaterThanOrEqual(1);

            
            console.log('Population Diagram correct')
        })

        it('Set status as To be Reviewed', async () => {
            console.log('Changing Status ...')

            await page.waitForSelector(selectors.STATUS_BUTTON, {hidden:false})
            await page.waitForSelector('button[aria-label="select merge strategy"]', {hidden:false})
            await page.click('button[aria-label="select merge strategy"]', {hidden:false})
            await page.waitForSelector('#split-button-menu')
            await page.keyboard.press('ArrowDown');
            await page.keyboard.press('Enter')
            await page.waitForTimeout(300)
            await page.click(selectors.STATUS_BUTTON)
            await page.waitForTimeout(3000)
        
            const sentence_status = await page.$$eval('span.MuiChip-label.MuiChip-labelSmall', status => {
                return status.map(status => status.innerText.toLowerCase());
            });

            expect(sentence_status).toContain("to be reviewed");
            await page.waitForSelector(selectors.BIOTECH_ICON_SELECTOR)
            await page.click(selectors.BIOTECH_ICON_SELECTOR)
            await page.waitForTimeout(2000)
            console.log('Status Changed')
        })

        it('Set status as NPO Approved', async () => {
            console.log('Changing Status ...')

            await page.waitForSelector(selectors.STATUS_BUTTON, {hidden:false})
            await page.waitForSelector('button[aria-label="select merge strategy"]', {hidden:false})
            await page.click('button[aria-label="select merge strategy"]')
            await page.waitForSelector('#split-button-menu', {hidden:false})
            await page.keyboard.press('ArrowDown');
            await page.keyboard.press('Enter')
            await page.waitForTimeout(1000)

            await page.click(selectors.STATUS_BUTTON)
            await page.waitForTimeout(3000)
        
            const sentence_final_status = await page.$$eval('span.MuiChip-label.MuiChip-labelSmall', status => {
                return status.map(status => status.innerText.toLowerCase());
            });

            expect(sentence_final_status).toContain("npo approved");
            console.log('Status Changed')
        })
    })

    
})