
export const LOGIN_PAGE= '.mat-form-field-infix'
export const USERNAME = 'input[formcontrolname="username"]'
export const PASSWORD = 'input[formcontrolname="password"]'
export const SIGN_IN_BUTTON = '#signin-button'
export const SEARCH_ICON = 'svg[data-testid="SearchIcon"]'
export const SEARCH_BAR = 'div:has(> input[placeholder="Search for Sentences"]'
export const ADD_RECORD = 'button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary'
export const ARTICLE_LABEL = 'input[placeholder="Enter Article Title"]'
export const ARTICLE_FIELD = 'div:has(> input[placeholder="Enter Article Title"]'
export const PMID_FIELD = 'div:has(> input[placeholder="Enter PMID"]'
export const PMCID_FIELD = 'div:has(> input[placeholder="Enter PMCID"]'
export const DOI_FIELD = 'div:has(> input[placeholder="Enter DOI"]'
export const SENTENCE_FIELD = 'div:has(> textarea[placeholder="Enter the sentence"]'
export const CREATE_SENTENCE = 'button[type="submit"][tabindex="0"]'
export const SENTENCE_DETAILS_TITLE = 'h3.MuiTypography-root.MuiTypography-h3'
export const SENTENCE_PAGE = 'h5.MuiTypography-root.MuiTypography-h5'
export const TABLE_ROW= 'div[data-rowindex="0"][role = "row"]'
export const ADD_KNOWLEDGE_STATEMENT ='button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-fullWidth.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-fullWidth'
export const SPECIES_FIELD ='div:has(> input[placeholder="Select Species"]'
export const KS_FIELD ='div:has(> textarea[placeholder="Enter Knowledge Statement"]'
export const PROVENANCE_FIELD ='div:has(> input[placeholder="Enter Provenances (Press Enter to add a Provenance)"]'
export const RIGHT_ROOT_LATERALITY ='span:has(> input[id="root_laterality-0"]'
export const IPSI_PROJECTION ='span:has(> input[id="root_projection-0"]'
export const SENSORY_CIRCUIT_TYPE ='span:has(> input[id="root_circuit_type-0"]'
export const APINATOMY_MODEL ='div:has(> input[placeholder="Enter Apinatomay Model Name"]'
export const ADDITIONAL_INFORMATION ='div:has(> textarea[placeholder="Enter additional information on the knowledge statement"]'
export const PROGRESS_LOADER = 'span[role="progressbar"]'
export const STATUS_BUTTON = 'div.MuiButtonGroup-root.MuiButtonGroup-contained'
export const PROOFING_TAB= 'button[role="tab"][aria-selected="false"]'
export const ORIGIN_FIELD= 'div:has(> input[placeholder="Select Origin"]'
export const NOT_SPECIFIED_BUTTON= 'div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl:has(> div.MuiSelect-select.MuiSelect-standard.MuiInputBase-input.MuiOutlinedInput-input'
export const ADD_VIA = 'button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textInfo.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-root.MuiButton-text.MuiButton-textInfo.MuiButton-sizeMedium.MuiButton-textSizeMedium'
export const VIA_FIELD= 'div:has(> input[placeholder="Select Via"]'
export const DESTINATION_FIELD= 'div:has(> input[placeholder="Select Destination"]'
export const TAGS_FIELD = 'div:has(> input[placeholder="Select Tags"]'
export const NOTES_FIELD = 'div:has(> textarea[placeholder="Write your note"]'
export const STATEMENT_PREVIEW = 'rect.nsewdrag.drag'
export const STATEMENT_PREVIEW_TITLE= 'h5.MuiTypography-root.MuiTypography-h5 + p.MuiTypography-root.MuiTypography-body1'
export const LOGOUT = 'button[aria-label="logout"]'
export const SEND_BUTTON = 'button[label= "Send"]'
export const STATUS_DROPDOWN = 'button[aria-label="select merge strategy"]'