version: "1.0"
stages:
  - clone
  - build
  - push
  - deploy
steps:
  main_clone:
    title: Clone main repository
    type: git-clone
    stage: clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'
    git: github
  buildComposer:
    title: "Building SCKAN Composer Docker Image"
    type: build
    image_name: "scidash"
    tag: "${{CF_BUILD_ID}}"
    dockerfile: "Dockerfile"
    # no_cache: true
    # no_cf_cache: true    
    registry: ${{REGISTRY}}
  deployComposer:
    title: Deploying SCKAN Composer
    stage: deploy
    image: codefresh/kubectl
    working_directory: ./k8s
    commands:
      - kubectl config get-contexts
      - kubectl config use-context $CLUSTER
      - kubectl config set-context $CLUSTER --namespace=$NAMESPACE
      - envsubst < postgres.yaml | kubectl apply -f -
      - envsubst < composer.yaml | kubectl apply -f -
      - envsubst < ingress.yaml | kubectl apply -f -
