apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: composer-media
  labels:
    app: composer-media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: composer
  labels:
    app: composer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composer
  template:
    metadata:
      labels:
        app: composer
        usesvolume: composer-media
    spec:
      containers:
      - name: composer
        image: us.gcr.io/metacellllc/sckan/composer:{{CF_BUILD_ID}}
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USER
          value: "{{DB_USER}}"
        - name: DB_PASSWORD
          value: "{{DB_PASSWORD}}"
        - name: DB_HOST
          value: "{{DB_HOST}}"
        - name: DB_NAME
          value: "{{DB_NAME}}"
        - name: DB_PORT
          value: "{{DB_PORT}}"
        - name: PRODUCTION
          value: "True"
        - name: DEBUG
          value: "{{DEBUG}}"
        ports:
        - containerPort: 8000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin/login/
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 30
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin/login/
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: composer-media
          mountPath: /usr/src/app/persistent
      volumes:
      - name: composer-media
        persistentVolumeClaim:
          claimName: composer-media
---
apiVersion: v1
kind: Service
metadata:
  name: composer
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: composer
