# apiVersion: v1
# kind: Secret
# metadata:
#   name: composer
# type: Opaque
# stringData:
#   SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: {{OAUTH_GOOGLE_KEY}}
#   SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: {{OAUTH_GOOGLE_SECRET}}
#   SOCIAL_AUTH_TWITTER_KEY: {{OAUTH_TWITTER_KEY}}
#   SOCIAL_AUTH_TWITTER_SECRET: {{OAUTH_TWITTER_SECRET}}
#   SOCIAL_AUTH_GITHUB_KEY: {{OAUTH_GITHUB_KEY}}
#   SOCIAL_AUTH_GITHUB_SECRET: {{OAUTH_GITHUB_SECRET}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: composer
  labels:
    app: sckan-composer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sckan-composer
  template:
    metadata:
      labels:
        app: sckan-composer
    spec:
      containers:
      - name: composer
        image: us.gcr.io/metacellllc/composer:{{TAG}}
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          value: ${DB_USER}
        - name: POSTGRES_PASSWORD
          value: ${DB_PASSWORD}
        - name: POSTGRES_DB
          value: ${DB_NAME}
        - name: PGPORT
          value: ${DB_PORT}
        ports:
        - containerPort: 8000
        volumeMounts:
        # - name: secrets
        #   mountPath: "/etc/secrets"
        #   readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: composer
---
apiVersion: v1
kind: Service
metadata:
  name: composer
  labels:
    app: sckan-composer
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: composer
