apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "letsencrypt-sckan-composer"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: filippo@metacell.us
    privateKeySecretRef:
      name: letsencrypt-sckan-composer
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-sckan-composer
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-keepalive-timeout: 600
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-read-timeout: 600
    nginx.ingress.kubernetes.io/proxy-send-timeout: 600
  name: sckan-composer-web-nginx-ingress
spec:
  rules:
  - host: "{{DOMAIN}}"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx
            port:
              number: 80
  tls:
  - hosts:
    - {{DOMAIN}}
    secretName: sckan-composer-tls
