apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        usesvolume: composer-media
    spec:
      containers:
      - name: nginx
        image: us.gcr.io/metacellllc/sckan/nginx:{{CF_BUILD_ID}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: composer-media
          mountPath: /usr/share/nginx/html/media/
          readOnly: true
      volumes:
      - name: composer-media
        persistentVolumeClaim:
          claimName: composer-media
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: usesvolume
                  operator: In
                  values:
                    - composer-media
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
