version: '1.0'
stages:
- prepare
- build
- unittest
- deploy
- qa
- publish
steps:
  main_clone:
    title: Clone main repository
    type: git-clone
    stage: prepare
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'
    git: github
  post_main_clone:
    title: Post main clone
    type: parallel
    stage: prepare
    steps:
      clone_cloud_harness:
        title: Cloning cloud-harness repository...
        type: git-clone
        stage: prepare
        repo: https://github.com/MetaCell/cloud-harness.git
        revision: '${{CLOUDHARNESS_BRANCH}}'
        working_directory: .
        git: github
  prepare_deployment:
    title: Prepare helm chart
    image: python:3.12
    stage: prepare
    working_directory: .
    commands:
    - bash cloud-harness/install.sh
    - harness-deployment cloud-harness . -d ${{DOMAIN}} -r ${{REGISTRY}} -rs '${{REGISTRY_SECRET}}'
      -n ${{NAMESPACE}} --write-env -e dev --cache-url '${{IMAGE_CACHE_URL}}' -i composer
    - cat deployment/.env >> ${{CF_VOLUME_PATH}}/env_vars_to_export
    - cat ${{CF_VOLUME_PATH}}/env_vars_to_export
  prepare_deployment_view:
    commands:
    - helm template ./deployment/helm --debug -n ${{NAMESPACE}}
    environment:
    - ACTION=auth
    - KUBE_CONTEXT=${{NAMESPACE}}
    image: codefresh/cfstep-helm:3.6.2
    stage: prepare
    title: View helm chart
  build_application_images_0:
    type: parallel
    stage: build
    steps:
      accounts:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        image_name: cloud-harness/accounts
        title: Accounts
        working_directory: ./cloud-harness/applications/accounts
        tags:
        - '${{ACCOUNTS_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{ACCOUNTS_TAG_EXISTS}}', '{{ACCOUNTS_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{ACCOUNTS_TAG_FORCE_BUILD}}', '{{ACCOUNTS_TAG_FORCE_BUILD}}')
                == false
      cloudharness-base:
        type: build
        stage: build
        dockerfile: infrastructure/base-images/cloudharness-base/Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        image_name: cloud-harness/cloudharness-base
        title: Cloudharness base
        working_directory: ./cloud-harness
        tags:
        - '${{CLOUDHARNESS_BASE_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{CLOUDHARNESS_BASE_TAG_EXISTS}}', '{{CLOUDHARNESS_BASE_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{CLOUDHARNESS_BASE_TAG_FORCE_BUILD}}', '{{CLOUDHARNESS_BASE_TAG_FORCE_BUILD}}')
                == false
      test-e2e:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        image_name: cloud-harness/test-e2e
        title: Test e2e
        working_directory: ./cloud-harness/test/test-e2e
        tags:
        - '${{TEST_E2E_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        - latest
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{TEST_E2E_TAG_EXISTS}}', '{{TEST_E2E_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{TEST_E2E_TAG_FORCE_BUILD}}', '{{TEST_E2E_TAG_FORCE_BUILD}}')
                == false
      cloudharness-frontend-build:
        type: build
        stage: build
        dockerfile: infrastructure/base-images/cloudharness-frontend-build/Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        image_name: cloud-harness/cloudharness-frontend-build
        title: Cloudharness frontend build
        working_directory: ./cloud-harness
        tags:
        - '${{CLOUDHARNESS_FRONTEND_BUILD_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{CLOUDHARNESS_FRONTEND_BUILD_TAG_EXISTS}}',
                '{{CLOUDHARNESS_FRONTEND_BUILD_TAG_EXISTS}}') == true
              forceNoCache: includes('${{CLOUDHARNESS_FRONTEND_BUILD_TAG_FORCE_BUILD}}',
                '{{CLOUDHARNESS_FRONTEND_BUILD_TAG_FORCE_BUILD}}') == false
      composer-notify:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        image_name: cloud-harness/composer-notify
        title: Composer notify
        working_directory: ./applications/composer/tasks/notify
        tags:
        - '${{COMPOSER_NOTIFY_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{COMPOSER_NOTIFY_TAG_EXISTS}}', '{{COMPOSER_NOTIFY_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{COMPOSER_NOTIFY_TAG_FORCE_BUILD}}', '{{COMPOSER_NOTIFY_TAG_FORCE_BUILD}}')
                == false
    title: Build parallel step 1
  build_application_images_1:
    type: parallel
    stage: build
    steps:
      test-api:
        type: build
        stage: build
        dockerfile: test/test-api/Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - CLOUDHARNESS_BASE=${{REGISTRY}}/cloud-harness/cloudharness-base:${{CLOUDHARNESS_BASE_TAG}}
        image_name: cloud-harness/test-api
        title: Test api
        working_directory: ./cloud-harness
        tags:
        - '${{TEST_API_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        - latest
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{TEST_API_TAG_EXISTS}}', '{{TEST_API_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{TEST_API_TAG_FORCE_BUILD}}', '{{TEST_API_TAG_FORCE_BUILD}}')
                == false
      cloudharness-django:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - CLOUDHARNESS_BASE=${{REGISTRY}}/cloud-harness/cloudharness-base:${{CLOUDHARNESS_BASE_TAG}}
        image_name: cloud-harness/cloudharness-django
        title: Cloudharness django
        working_directory: ./cloud-harness/infrastructure/common-images/cloudharness-django
        tags:
        - '${{CLOUDHARNESS_DJANGO_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{CLOUDHARNESS_DJANGO_TAG_EXISTS}}', '{{CLOUDHARNESS_DJANGO_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{CLOUDHARNESS_DJANGO_TAG_FORCE_BUILD}}', '{{CLOUDHARNESS_DJANGO_TAG_FORCE_BUILD}}')
                == false
    title: Build parallel step 2
  build_application_images_2:
    type: parallel
    stage: build
    steps:
      composer:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - CLOUDHARNESS_FRONTEND_BUILD=${{REGISTRY}}/cloud-harness/cloudharness-frontend-build:${{CLOUDHARNESS_FRONTEND_BUILD_TAG}}
        - CLOUDHARNESS_DJANGO=${{REGISTRY}}/cloud-harness/cloudharness-django:${{CLOUDHARNESS_DJANGO_TAG}}
        image_name: cloud-harness/composer
        title: Composer
        working_directory: ./applications/composer
        tags:
        - '${{COMPOSER_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{COMPOSER_TAG_EXISTS}}', '{{COMPOSER_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{COMPOSER_TAG_FORCE_BUILD}}', '{{COMPOSER_TAG_FORCE_BUILD}}')
                == false
    title: Build parallel step 3
  build_application_images_3:
    type: parallel
    stage: build
    steps:
      composer-neurondm:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - COMPOSER=${{REGISTRY}}/cloud-harness/composer:${{COMPOSER_TAG}}
        image_name: cloud-harness/composer-neurondm
        title: Composer neurondm
        working_directory: ./applications/composer/tasks/neurondm
        tags:
        - '${{COMPOSER_NEURONDM_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{COMPOSER_NEURONDM_TAG_EXISTS}}', '{{COMPOSER_NEURONDM_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{COMPOSER_NEURONDM_TAG_FORCE_BUILD}}', '{{COMPOSER_NEURONDM_TAG_FORCE_BUILD}}')
                == false
    title: Build parallel step 4
  deployment:
    stage: deploy
    type: helm
    working_directory: ./${{CF_REPO_NAME}}
    title: Installing chart
    arguments:
      helm_version: 3.6.2
      chart_name: deployment/helm
      release_name: '${{NAMESPACE}}'
      kube_context: '${{CLUSTER_NAME}}'
      namespace: '${{NAMESPACE}}'
      chart_version: '${{CF_BUILD_ID}}'
      cmd_ps: --wait --timeout 600s --create-namespace
      custom_value_files:
      - ./deployment/helm/values.yaml
      custom_values:
      - apps_composer_harness_secrets_SECRET__KEY=${{SECRET__KEY}}
      - apps_composer_harness_secrets_SOCIAL__AUTH__ORCID__SECRET=${{SOCIAL__AUTH__ORCID__SECRET}}
  wait_deployment:
    stage: qa
    title: Wait deployment to be ready
    image: codefresh/kubectl
    commands:
    - kubectl config use-context ${{CLUSTER_NAME}}
    - kubectl config set-context --current --namespace=${{NAMESPACE}}
    - kubectl rollout status deployment/accounts
    - kubectl rollout status deployment/argo-gk
    - kubectl rollout status deployment/composer
    - sleep 60
    when:
      condition:
        all:
          whenVarExists: includes("${{SKIP_TESTS}}", "{{SKIP_TESTS}}") == true
  approval:
    type: pending-approval
    stage: publish
    title: Approve build
    description: Approve build release and tagging
    timeout:
      duration: 168
      finalState: denied
  publish:
    type: parallel
    stage: publish
    steps:
      publish_cloudharness-frontend-build:
        stage: publish
        type: push
        title: Cloudharness frontend build
        candidate: '${{REGISTRY}}/cloud-harness/cloudharness-frontend-build:${{CLOUDHARNESS_FRONTEND_BUILD_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_cloudharness-base:
        stage: publish
        type: push
        title: Cloudharness base
        candidate: '${{REGISTRY}}/cloud-harness/cloudharness-base:${{CLOUDHARNESS_BASE_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_cloudharness-django:
        stage: publish
        type: push
        title: Cloudharness django
        candidate: '${{REGISTRY}}/cloud-harness/cloudharness-django:${{CLOUDHARNESS_DJANGO_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_accounts:
        stage: publish
        type: push
        title: Accounts
        candidate: '${{REGISTRY}}/cloud-harness/accounts:${{ACCOUNTS_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_composer:
        stage: publish
        type: push
        title: Composer
        candidate: '${{REGISTRY}}/cloud-harness/composer:${{COMPOSER_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_composer-neurondm:
        stage: publish
        type: push
        title: Composer neurondm
        candidate: '${{REGISTRY}}/cloud-harness/composer-neurondm:${{COMPOSER_NEURONDM_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_composer-notify:
        stage: publish
        type: push
        title: Composer notify
        candidate: '${{REGISTRY}}/cloud-harness/composer-notify:${{COMPOSER_NOTIFY_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
    when:
      condition:
        all:
          whenVarExists: includes("${{DEPLOYMENT_PUBLISH_TAG}}", "{{DEPLOYMENT_PUBLISH_TAG}}")
            == false
