FROM ghcr.io/puppeteer/puppeteer:latest

COPY frontend/package.json .
COPY frontend/package-lock.json .

RUN npm ci

USER pptruser
COPY --chown=pptruser:pptruser frontend frontend
	
ENV TEST_URL=https://composer.sckan.dev.metacell.us/



