# Generated by Django 4.1.4 on 2023-01-13 09:26

import composer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0003_remove_sentence_sentence_pmid_pmcd_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="doi",
            field=composer.models.DoiField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
    ]
