# Generated by Django 4.1.4 on 2023-04-18 09:08

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


def update_laterality(apps, schema_editor):
        ConnectivityStatement = apps.get_model('composer', 'ConnectivityStatement')
        ConnectivityStatement.objects.all().update(projection=F("laterality"))
        ConnectivityStatement.objects.all().update(laterality="UNKNOWN")


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0003_alter_via_display_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnsDivision",
            new_name="Phenotype",
        ),
        migrations.RenameModel(
            old_name="BiologicalSex",
            new_name="Sex",
        ),
        migrations.AlterModelOptions(
            name="phenotype",
            options={"ordering": ["name"], "verbose_name_plural": "Phenotypes"},
        ),
        migrations.AlterModelOptions(
            name="sex",
            options={"ordering": ["name"], "verbose_name_plural": "Sex"},
        ),
        migrations.RemoveConstraint(
            model_name="connectivitystatement",
            name="laterality_valid",
        ),
        migrations.RenameField(
            model_name="connectivitystatement",
            old_name="biological_sex",
            new_name="sex",
        ),
        migrations.RemoveField(
            model_name="connectivitystatement",
            name="ans_division",
        ),
        migrations.AddField(
            model_name="connectivitystatement",
            name="phenotype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="composer.phenotype",
                verbose_name="Phenotype",
            ),
        ),
        migrations.AddField(
            model_name="connectivitystatement",
            name="projection",
            field=models.CharField(
                choices=[
                    ("IPSI", "Ipsi"),
                    ("CONTRAT", "Contrat"),
                    ("BI", "Bilateral"),
                    ("UNKNOWN", "Not specified"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="connectivitystatement",
            name="laterality",
            field=models.CharField(
                choices=[
                    ("RIGHT", "Right"),
                    ("LEFT", "Left"),
                    ("UNKNOWN", "Not specified"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.RunPython(update_laterality),
        migrations.AddConstraint(
            model_name="connectivitystatement",
            constraint=models.CheckConstraint(
                check=models.Q(("laterality__in", ["RIGHT", "LEFT", "UNKNOWN"])),
                name="laterality_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="connectivitystatement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("projection__in", ["IPSI", "CONTRAT", "BI", "UNKNOWN"])
                ),
                name="projection_valid",
            ),
        ),
    ]
