# Generated by Django 4.1.4 on 2022-12-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0004_connectivitystatement_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectivitystatement',
            name='path',
            field=models.ManyToManyField(through='composer.Via', to='composer.anatomicalentity', verbose_name='Path'),
        ),
    ]
