# Generated by Django 4.1.4 on 2023-01-13 11:09

from django.db import migrations

import composer.models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0004_sentence_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doi",
            name="doi",
            field=composer.models.DoiField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="doi",
            field=composer.models.DoiField(
                blank=True, db_index=True, max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="pmcid",
            field=composer.models.PmcIdField(
                blank=True, db_index=True, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="pmid",
            field=composer.models.PmIdField(blank=True, db_index=True, null=True),
        ),
    ]
