# Generated by Django 4.1.4 on 2023-01-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0005_alter_doi_doi_alter_sentence_doi_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sentence",
            name="sentence_pmid_pmcd_valid",
        ),
        migrations.AddConstraint(
            model_name="sentence",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("state", "compose_now"), _negated=True),
                    models.Q(
                        ("state", "compose_now"),
                        models.Q(
                            ("pmid__isnull", False),
                            ("pmcid__isnull", False),
                            ("doi__isnull", False),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="sentence_pmid_pmcd_valid",
            ),
        ),
    ]
