# Generated by Django 4.1.4 on 2022-12-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0005_connectivitystatement_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isCurator',
            new_name='is_curator',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='isReviewer',
            new_name='is_reviewer',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='isTriageOperator',
            new_name='is_triageOperator',
        ),
    ]
