# Generated by Django 4.1.4 on 2023-04-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0006_add_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.URLField()),
                (
                    "connectivity_statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composer.connectivitystatement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Provenances",
            },
        ),
    ]
