# Generated by Django 4.1.4 on 2023-01-13 15:24

import composer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0007_alter_sentence_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doi",
            name="doi",
            field=composer.models.DoiField(max_length=100),
        ),
    ]
