# Generated by Django 4.1.4 on 2023-01-15 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("composer", "0008_alter_doi_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectivitystatement",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Curator",
            ),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Triage Operator",
            ),
        ),
    ]
