# Generated by Django 4.1.4 on 2022-12-30 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('composer', '0008_alter_via_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivitystatement',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Curator'),
        ),
    ]
