# Generated by Django 4.1.4 on 2022-12-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0009_alter_connectivitystatement_curator'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Note Tags',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('connectivity_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='composer.connectivitystatement', verbose_name='Connectivity Statement')),
                ('provenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='composer.provenance', verbose_name='Provenance')),
                ('tags', models.ManyToManyField(to='composer.notetag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'ordering': ['note'],
            },
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('connectivity_statement__isnull', True), ('provenance__isnull', False)), models.Q(('connectivity_statement__isnull', False), ('provenance__isnull', True)), _connector='OR'), name='only_provenance_or_connectivity_statement'),
        ),
    ]
