# Generated by Django 4.1.4 on 2023-01-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0009_alter_connectivitystatement_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectivitystatement",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sentence",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
