# Generated by Django 4.1.4 on 2023-01-25 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0010_connectivitystatement_modified_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
