# Generated by Django 4.1.4 on 2023-02-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0012_alter_via_options_rename_ordering_via_display_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="created",
            new_name="created_at",
        ),
    ]
