# Generated by Django 4.1.4 on 2023-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0013_rename_created_note_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="batch_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sentence",
            name="external_ref",
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="text",
            field=models.TextField(),
        ),
    ]
