# Generated by Django 4.1.4 on 2023-02-10 08:08

from django.db import migrations, models


def update_external_ref(apps, schema_editor):
    # Set the external_ref field to the id field
    Sentence = apps.get_model("composer", "Sentence")
    db_alias = schema_editor.connection.alias
    Sentence.objects.using(db_alias).all().update(external_ref=models.F("id"))


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0014_sentence_batch_name_sentence_external_ref_and_more"),
    ]

    operations = [
        migrations.RunPython(update_external_ref),
        migrations.AlterField(
            model_name="sentence",
            name="external_ref",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
