# Generated by Django 4.1.4 on 2023-06-01 11:03

from django.db import migrations

def update_reference_uri_value(apps, schema_editor):
    ConnectivityStatement = apps.get_model('composer', 'ConnectivityStatement')
    for cs in ConnectivityStatement.objects.all():
        cs.reference_uri = f"http://uri.interlex.org/tgbugs/uris/readable/sparc-nlp/composer/{cs.pk}"
        cs.save()


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0014_connectivitystatement_reference_uri"),
    ]

    operations = [
         migrations.RunPython(update_reference_uri_value),
    ]
