# Generated by Django 4.1.4 on 2023-06-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0015_update_reference_uri"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionalCircuitRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("ontology_uri", models.URLField()),
            ],
            options={
                "verbose_name_plural": "Funtional Circuit Roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectionPhenotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("ontology_uri", models.URLField()),
            ],
            options={
                "verbose_name_plural": "Projection Phenotypes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="connectivitystatement",
            name="functional_circuit_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="composer.functionalcircuitrole",
            ),
        ),
        migrations.AddField(
            model_name="connectivitystatement",
            name="projection_phenotype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="composer.projectionphenotype",
            ),
        ),
    ]
