# Generated by Django 4.1.4 on 2023-02-14 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0016_biologicalsex_specie_uri_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biologicalsex",
            old_name="uri",
            new_name="ontology_uri",
        ),
        migrations.RenameField(
            model_name="specie",
            old_name="uri",
            new_name="ontology_uri",
        ),
    ]
