# Generated by Django 4.1.4 on 2023-06-01 14:57

from django.db import migrations


def add_functional_circuit_roles(apps, schema_editor):
        FunctionalCircuitRole = apps.get_model('composer', 'FunctionalCircuitRole')
        roles = [FunctionalCircuitRole(name = 'Inhibitory', ontology_uri = 'http://uri.interlex.org/base/ilx_0105486'), FunctionalCircuitRole(name = 'Excitatory', ontology_uri = 'http://uri.interlex.org/base/ilx_0104003') ]
        FunctionalCircuitRole.objects.bulk_create(roles)

def add_projection_phenotypes(apps, schema_editor):
        ProjectionPhenotype = apps.get_model('composer', 'ProjectionPhenotype')
        projection_list = [
               ProjectionPhenotype(name = 'Spinal cord descending projection phenotype', ontology_uri = 'http://uri.interlex.org/tgbugs/uris/readable/SpinalCordDescendingProjectionPhenotype'), ProjectionPhenotype(name = 'Spinal cord ascending projection phenotype', ontology_uri = 'http://uri.interlex.org/tgbugs/uris/readable/SpinalCordAscendingProjectionPhenotype'),
               ProjectionPhenotype(name = 'Intestino fugal projection phenotype', ontology_uri = 'http://uri.interlex.org/tgbugs/uris/readable/IntestinoFugalProjectionPhenotype'), ProjectionPhenotype(name = 'Anterior projecting', ontology_uri = 'http://uri.interlex.org/tgbugs/uris/readable/AnteriorProjecting'),
               ProjectionPhenotype(name = 'Posterior projecting', ontology_uri = 'http://uri.interlex.org/tgbugs/uris/readable/PosteriorProjecting')
                            ]
        ProjectionPhenotype.objects.bulk_create(projection_list)


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0016_functionalcircuitrole_projectionphenotype_and_more"),
    ]

    operations = [
        migrations.RunPython(add_functional_circuit_roles),
        migrations.RunPython(add_projection_phenotypes),
    ]
