# Generated by Django 4.1.4 on 2023-01-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0016_alter_connectivitystatement_destination_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='connectivitystatement',
            name='laterality_valid',
        ),
        migrations.RemoveConstraint(
            model_name='connectivitystatement',
            name='circuit_type_valid',
        ),
        migrations.AlterField(
            model_name='connectivitystatement',
            name='circuit_type',
            field=models.CharField(choices=[('SENSORY', 'Sensory'), ('MOTOR', 'Motor'), ('INTRINSIC', 'Intrinsic'), ('PROJECTION', 'Projection'), ('ANAXONIC', 'Anaxonic'), ('UNKNOWN', 'Not specified')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='connectivitystatement',
            name='destination_type',
            field=models.CharField(choices=[('AXON-SE', 'Axon sensory ending'), ('AXON-T', 'Axon terminal'), ('AXON-ST', 'Axon sensory terminal'), ('UNKNOW', 'Not specified')], default='UNKNOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='connectivitystatement',
            name='laterality',
            field=models.CharField(choices=[('IPSI', 'Ipsi'), ('ONTRAT', 'Contrat'), ('BI', 'Bilateral'), ('UNKNOWN', 'Not specified')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='connectivitystatement',
            constraint=models.CheckConstraint(check=models.Q(('laterality__in', ['IPSI', 'ONTRAT', 'BI', 'UNKNOWN'])), name='laterality_valid'),
        ),
        migrations.AddConstraint(
            model_name='connectivitystatement',
            constraint=models.CheckConstraint(check=models.Q(('circuit_type__in', ['SENSORY', 'MOTOR', 'INTRINSIC', 'PROJECTION', 'ANAXONIC', 'UNKNOWN'])), name='circuit_type_valid'),
        ),
    ]
