# Generated by Django 4.1.4 on 2023-02-13 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0016_biologicalsex_specie_uri_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biologicalsex",
            name="uri",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="http://purl.obolibrary.org/obo/PATO_\\d*"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="specie",
            name="uri",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="http://purl.obolibrary.org/obo/NCBITaxon_\\d*"
                    )
                ],
            ),
        ),
    ]
