# Generated by Django 4.1.4 on 2023-06-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0017_auto_20230601_1657"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="note",
            name="note_type_valid",
        ),
        migrations.AlterField(
            model_name="note",
            name="type",
            field=models.CharField(
                choices=[
                    ("plain", "Plain"),
                    ("different", "Different"),
                    ("transition", "Transition"),
                    ("alert", "Alert"),
                ],
                default="plain",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("type__in", ["plain", "different", "transition", "alert"])
                ),
                name="note_type_valid",
            ),
        ),
    ]
