# Generated by Django 4.1.4 on 2023-01-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0017_remove_connectivitystatement_laterality_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectivitystatement",
            name="species",
            field=models.ManyToManyField(
                null=True, to="composer.specie", verbose_name="Species"
            ),
        ),
    ]
