# Generated by Django 4.1.4 on 2023-03-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0017_rename_uri_biologicalsex_ontology_uri_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentence",
            name="external_ref",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name="sentence",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("external_ref__isnull", True), ("batch_name__isnull", True)
                    ),
                    models.Q(
                        ("external_ref__isnull", False), ("batch_name__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="sentence_externalref_and_batch_valid",
            ),
        ),
    ]
