# Generated by Django 4.1.4 on 2023-06-08 10:35

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0018_remove_note_note_type_valid_alter_note_type_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="anatomicalentity",
            index=models.Index(
                django.db.models.functions.text.Upper("name"),
                name="anatomicalentity_upper_name",
            ),
        ),
    ]
