# Generated by Django 4.1.4 on 2023-03-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0019_alter_connectivitystatement_knowledge_statement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Notes"},
        ),
        migrations.AddField(
            model_name="tag",
            name="exportable",
            field=models.BooleanField(default=False),
        ),
    ]
