# Generated by Django 4.1.4 on 2023-01-03 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0019_alter_connectivitystatement_species"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectivitystatement",
            name="ans_division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="composer.ansdivision",
                verbose_name="ANS Division",
            ),
        ),
    ]
