# Generated by Django 4.1.4 on 2023-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0020_alter_note_options_tag_exportable"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="type",
            field=models.CharField(
                choices=[
                    ("plain", "Plain"),
                    ("species_different", "Species Different"),
                ],
                default="plain",
                max_length=20,
            ),
        ),
    ]
