# Generated by Django 4.1.4 on 2023-03-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0022_via_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="connectivitystatement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("destination_type__in", ["AXON-SE", "AXON-T", "AXON-ST", "UNKNOW"])
                ),
                name="destination_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                check=models.Q(("type__in", ["plain", "different"])),
                name="note_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="via",
            constraint=models.CheckConstraint(
                check=models.Q(("type__in", ["AXON", "DENDRITE"])),
                name="via_type_valid",
            ),
        ),
    ]
