# Generated by Django 4.1.4 on 2023-10-23 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0023_auto_20231023_1532"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectivitystatement",
            name="origin",
        ),
    ]
