# Generated by Django 4.1.4 on 2023-01-11 16:59
import os

from django.contrib.auth.models import User
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0023_connectivitystatement_destination_type_valid_and_more"),
    ]

    def drop_admin_user(apps, schema_editor):        
        User.objects.filter(username="admin").delete()

    def generate_system_user(apps, schema_editor):
        User.objects.create_user(
            username="system",
            email="do_not_remove@system_user.com",
            password="system",
            first_name="System",
            last_name="User",
            is_staff=True,
        ).save()

    operations = [
        migrations.RunPython(generate_system_user),
        migrations.RunPython(drop_admin_user),
    ]
