# Generated by Django 4.1.4 on 2023-10-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0024_remove_connectivitystatement_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectivitystatement",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="old_destination",
                to="composer.anatomicalentity",
                verbose_name="Destination",
            ),
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AXON-T", "Axon terminal"),
                            ("AFFERENT-T", "Afferent terminal"),
                            ("UNKNOWN", "Not specified"),
                        ],
                        default="UNKNOWN",
                        max_length=12,
                    ),
                ),
                (
                    "anatomical_entities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="connection_layers",
                        to="composer.anatomicalentity",
                    ),
                ),
                (
                    "connectivity_statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="composer.connectivitystatement",
                    ),
                ),
                (
                    "from_entities",
                    models.ManyToManyField(blank=True, to="composer.anatomicalentity"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
