# Generated by Django 4.1.4 on 2023-01-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0025_remove_connectivitystatement_state_valid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provenance',
            name='uri',
        ),
        migrations.AddField(
            model_name='provenance',
            name='pmcid',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='pmid',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='provenance',
            constraint=models.CheckConstraint(check=models.Q(('pmid__isnull', False), ('pmcid__isnull', False), _connector='OR'), name='provenance_pmid_pmcd_valid'),
        ),
    ]
