# Generated by Django 4.1.4 on 2023-10-23 18:02

from django.db import migrations


def migrate_to_destination(apps, schema_editor):
    ConnectivityStatement = apps.get_model('composer', 'ConnectivityStatement')
    Destination = apps.get_model('composer', 'Destination')

    for statement in ConnectivityStatement.objects.all():
        destination = Destination.objects.create(
            connectivity_statement=statement,
            type=statement.destination_type
        )
        destination.anatomical_entities.add(statement.destination)
        destination.from_entities.set(statement.origins.all())


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0025_alter_connectivitystatement_destination_destination"),
    ]

    operations = [
        migrations.RunPython(migrate_to_destination),
    ]
