# Generated by Django 4.1.4 on 2023-04-06 15:06

from django.db import migrations

from composer.models import ConnectivityStatement


def update_destination_type(apps, schema_editor):
    # Update existing records with removed options to the new one
    ConnectivityStatement.objects.filter(
        destination_type__in=["AXON-SE", "AXON-ST"]
    ).update(destination_type="AFFERENT-T")

    # Update existing records with typo
    ConnectivityStatement.objects.filter(
        destination_type__in=["UNKNOW"]
    ).update(destination_type="UNKNOWN")


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0025_remove_connectivitystatement_state_valid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectivitystatement',
            options={'constraints': []},
        ),
        migrations.RunPython(update_destination_type),
    ]
