# Generated by Django 4.1.4 on 2023-10-24 01:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0026_auto_20231023_1802"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectivitystatement",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="connectivitystatement",
            name="destination_type",
        ),
    ]
