# Generated by Django 4.1.4 on 2023-04-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0026_remove_connectivitystatement_destination_type_valid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connectivitystatement",
            options={"verbose_name_plural": "Connectivity Statements"},
        ),
        migrations.AlterModelOptions(
            name="exportbatch",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Export Batches",
            },
        ),
        migrations.AlterField(
            model_name="connectivitystatement",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="connectivitystatement",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
