# Generated by Django 4.1.4 on 2023-04-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0028_alter_connectivitystatement_destination_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentence",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
