# Generated by Django 4.1.4 on 2023-10-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0027_remove_connectivitystatement_destination_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="connectivitystatement",
            name="destination_type_valid",
        ),
        migrations.AddConstraint(
            model_name="destination",
            constraint=models.CheckConstraint(
                check=models.Q(("type__in", ["AXON-T", "AFFERENT-T", "UNKNOWN"])),
                name="destination_type_valid",
            ),
        ),
    ]
