# Generated by Django 4.1.4 on 2023-01-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0027_doi"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doi",
            options={"ordering": ["doi"], "verbose_name_plural": "D.O.I.s"},
        ),
        migrations.RemoveField(
            model_name="connectivitystatement",
            name="uri",
        ),
    ]
