# Generated by Django 4.1.4 on 2023-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0027_alter_connectivitystatement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectivitystatement",
            name="destination_type",
            field=models.CharField(
                choices=[
                    ("AXON-T", "Axon terminal"),
                    ("AFFERENT-T", "Afferent terminal"),
                    ("UNKNOWN", "Not specified"),
                ],
                default="UNKNOWN",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="connectivitystatement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("destination_type__in", ["AXON-T", "AFFERENT-T", "UNKNOWN"])
                ),
                name="destination_type_valid",
            ),
        ),
    ]
