# Generated by Django 4.1.4 on 2023-10-24 14:36

from django.db import migrations


def migrate_data_forward(apps, schema_editor):
    Via = apps.get_model('composer', 'Via')
    for via in Via.objects.all():
        if via.anatomical_entity:
            via.anatomical_entities.add(via.anatomical_entity)
        via.order = via.display_order
        via.save()


def migrate_data_backward(apps, schema_editor):
    Via = apps.get_model('composer', 'Via')
    for via in Via.objects.all():
        via.anatomical_entity = via.anatomical_entities.first()
        via.display_order = via.order
        via.save()


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0028_via_anatomical_entities_via_order_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_data_forward, migrate_data_backward)
    ]
