# Generated by Django 4.1.4 on 2023-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0028_alter_sentence_created_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connectivitystatement",
            options={
                "ordering": ["-modified_date"],
                "verbose_name_plural": "Connectivity Statements",
            },
        ),
        migrations.RemoveConstraint(
            model_name="note",
            name="note_type_valid",
        ),
        migrations.AlterField(
            model_name="note",
            name="type",
            field=models.CharField(
                choices=[
                    ("plain", "Plain"),
                    ("different", "Different"),
                    ("transition", "Transition"),
                ],
                default="plain",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                check=models.Q(("type__in", ["plain", "different", "transition"])),
                name="note_type_valid",
            ),
        ),
    ]
