# Generated by Django 4.1.4 on 2023-04-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0029_alter_connectivitystatement_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connectivitystatement",
            options={
                "ordering": ["-modified_date"],
                "verbose_name_plural": "Connectivity Statements",
            },
        ),
        migrations.CreateModel(
            name="ExportMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("compose_now", "compose_now"),
                            ("curated", "Curated"),
                            ("excluded", "Excluded"),
                            ("rejected", "Rejected"),
                            ("to_be_reviewed", "to_be_reviewed"),
                            ("connection_missing", "Connection Missing"),
                            ("npo_approved", "Npo Approved"),
                            ("exported", "Exported"),
                        ],
                        max_length=18,
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "export_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composer.exportbatch",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Export Metrics",
            },
        ),
        migrations.AddConstraint(
            model_name="exportmetrics",
            constraint=models.UniqueConstraint(
                fields=("export_batch", "state"), name="unique_state_per_export_batch"
            ),
        ),
    ]
