# Generated by Django 4.1.4 on 2023-04-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0029_alter_connectivitystatement_options_exportmetrics_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="exportmetrics",
            name="unique_state_per_export_batch",
        ),
        migrations.AddField(
            model_name="exportmetrics",
            name="entity",
            field=models.CharField(
                choices=[
                    ("sentence", "Sentence"),
                    ("connectivity statement", "Connectivity Statement"),
                ],
                default="sentence",
                max_length=22,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="exportmetrics",
            constraint=models.UniqueConstraint(
                fields=("export_batch", "entity", "state"),
                name="unique_state_per_export_batch",
            ),
        ),
    ]
