# Generated by Django 4.1.4 on 2023-11-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "composer",
            "0030_alter_via_options_remove_connectivitystatement_path_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="via",
            name="order",
            field=models.IntegerField(),
        ),
    ]
