# Generated by Django 4.1.4 on 2023-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "composer",
            "0030_remove_exportmetrics_unique_state_per_export_batch_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportmetrics",
            name="state",
            field=models.CharField(max_length=18),
        ),
    ]
