# Generated by Django 4.1.4 on 2023-11-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "composer",
            "0030_alter_via_options_remove_connectivitystatement_path_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentence",
            options={"ordering": ["text"], "verbose_name_plural": "Sentences"},
        ),
        migrations.AlterField(
            model_name="via",
            name="order",
            field=models.IntegerField(),
        ),
    ]
