# Generated by Django 4.1.4 on 2023-01-09 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("composer", "0030_rename_curator_connectivitystatement_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="is_triageOperator",
            new_name="is_triage_operator",
        ),
        migrations.AlterField(
            model_name="provenance",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Triage Operator",
            ),
        ),
    ]
