# Generated by Django 4.1.4 on 2023-11-12 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0031_alter_via_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="via",
            unique_together=set(),
        ),
    ]
