# Generated by Django 4.1.4 on 2023-01-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "composer",
            "0031_rename_is_triageoperator_profile_is_triage_operator_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="provenance",
            name="provenance_pmid_pmcd_unique",
        ),
    ]
