# Generated by Django 4.1.4 on 2023-04-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0031_alter_exportmetrics_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportbatch",
            name="connectivity_statements_created",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exportbatch",
            name="sentences_created",
            field=models.IntegerField(default=0),
        ),
    ]
