# Generated by Django 4.1.4 on 2023-01-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0032_remove_provenance_provenance_pmid_pmcd_unique"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NoteTag",
            new_name="Tag",
        ),
        migrations.RemoveField(
            model_name="note",
            name="tags",
        ),
        migrations.AddField(
            model_name="connectivitystatement",
            name="tags",
            field=models.ManyToManyField(to="composer.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="provenance",
            name="tags",
            field=models.ManyToManyField(to="composer.tag", verbose_name="Tags"),
        ),
        migrations.AlterField(
            model_name="connectivitystatement",
            name="path",
            field=models.ManyToManyField(
                blank=True, through="composer.Via", to="composer.anatomicalentity"
            ),
        ),
        migrations.AlterField(
            model_name="via",
            name="anatomical_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="composer.anatomicalentity",
            ),
        ),
        migrations.AlterField(
            model_name="via",
            name="connectivity_statement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="composer.connectivitystatement",
            ),
        ),
    ]
