# Generated by Django 4.1.4 on 2023-04-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0033_enum_states_replace_underscore_with_space"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exportmetrics",
            options={"ordering": ["id"], "verbose_name_plural": "Export Metrics"},
        ),
        migrations.AlterField(
            model_name="exportbatch",
            name="connectivity_statements",
            field=models.ManyToManyField(
                help_text="Connectivity statements in this export batch",
                to="composer.connectivitystatement",
            ),
        ),
        migrations.AlterField(
            model_name="exportbatch",
            name="connectivity_statements_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of connectivity statements created since the previous export",
            ),
        ),
        migrations.AlterField(
            model_name="exportbatch",
            name="sentences_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of sentences created since the previous export",
            ),
        ),
    ]
