# Generated by Django 4.1.4 on 2024-01-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0033_alter_connectivitystatement_reference_uri"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="connectivitystatement",
            name="state_valid",
        ),
        migrations.AddConstraint(
            model_name="connectivitystatement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "state__in",
                        [
                            "draft",
                            "compose_now",
                            "curated",
                            "excluded",
                            "rejected",
                            "to_be_reviewed",
                            "connection_missing",
                            "npo_approved",
                            "exported",
                            "invalid",
                        ],
                    )
                ),
                name="state_valid",
            ),
        ),
    ]
