# Generated by Django 4.1.4 on 2023-01-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0033_rename_notetag_tag_remove_note_tags_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["tag"], "verbose_name_plural": "Tags"},
        ),
    ]
