# Generated by Django 4.1.4 on 2023-01-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0034_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectivitystatement",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="composer.tag", verbose_name="Tags"
            ),
        ),
        migrations.AlterField(
            model_name="provenance",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="composer.tag", verbose_name="Tags"
            ),
        ),
    ]
