# Generated by Django 4.1.4 on 2023-01-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0035_alter_provenance_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectivitystatement",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, to="composer.tag", verbose_name="Tags"
            ),
        ),
    ]
