# Generated by Django 4.1.4 on 2024-03-16 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0044_remove_anatomicalentity_ae_unique_upper_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "anatomicalentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="composer.anatomicalentity",
                    ),
                ),
            ],
            bases=("composer.anatomicalentity",),
        ),
        migrations.AlterField(
            model_name="anatomicalentity",
            name="ontology_uri",
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "anatomicalentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="composer.anatomicalentity",
                    ),
                ),
                (
                    "associated_layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="composer.layer",
                    ),
                ),
            ],
            bases=("composer.anatomicalentity",),
        ),
    ]
