# Generated by Django 4.1.4 on 2024-03-18 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0044_remove_anatomicalentity_ae_unique_upper_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="synonym",
            unique_together={("anatomical_entity", "name")},
        ),
    ]
