# Generated by Django 4.1.4 on 2024-03-14 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0044_remove_anatomicalentity_ae_unique_upper_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "anatomicalentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="composer.anatomicalentity",
                    ),
                ),
            ],
            bases=("composer.anatomicalentity",),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "anatomicalentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="composer.anatomicalentity",
                    ),
                ),
            ],
            bases=("composer.anatomicalentity",),
        ),
        migrations.CreateModel(
            name="RegionLayerPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="composer.layer"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composer.region",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="region",
            name="layers",
            field=models.ManyToManyField(
                through="composer.RegionLayerPair", to="composer.layer"
            ),
        ),
    ]
