# Generated by Django 4.1.4 on 2024-03-19 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0047_auto_20240319_1414"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectivitystatement",
            name="origins",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="anatomical_entities",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="from_entities",
        ),
        migrations.RemoveField(
            model_name="via",
            name="anatomical_entities",
        ),
        migrations.RemoveField(
            model_name="via",
            name="from_entities",
        ),
        migrations.AlterUniqueTogether(
            name="synonym",
            unique_together={("anatomical_entity_new", "name")},
        ),
        migrations.RemoveField(
            model_name="synonym",
            name="anatomical_entity",
        ),
        migrations.DeleteModel(
            name="AnatomicalEntity",
        ),
    ]
