# Generated by Django 4.1.4 on 2024-03-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0048_remove_connectivitystatement_origins_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnatomicalEntityNew",
            new_name="AnatomicalEntity",
        ),
        migrations.RenameField(
            model_name="destination",
            old_name="from_entities_new",
            new_name="from_entities",
        ),
        migrations.RenameField(
            model_name="via",
            old_name="anatomical_entities_new",
            new_name="anatomical_entities",
        ),
        migrations.RenameField(
            model_name="via",
            old_name="from_entities_new",
            new_name="from_entities",
        ),
        migrations.RenameField(
            model_name="connectivitystatement",
            old_name="origins_new",
            new_name="origins",
        ),
        migrations.RenameField(
            model_name="destination",
            old_name="anatomical_entities_new",
            new_name="anatomical_entities",
        ),
        migrations.RenameField(
            model_name="synonym",
            old_name="anatomical_entity_new",
            new_name="anatomical_entity",
        ),
        migrations.AlterUniqueTogether(
            name="synonym",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="synonym",
            unique_together={("anatomical_entity", "name")},
        ),
    ]
