# Generated by Django 4.1.4 on 2024-03-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0049_rename_anatomicalentitynew_anatomicalentity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anatomicalentity",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Anatomical Entities Meta",
            },
        ),
        migrations.AlterModelOptions(
            name="anatomicalentitymeta",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Anatomical Entities Meta",
            },
        ),
        migrations.AlterField(
            model_name="connectivitystatement",
            name="origins",
            field=models.ManyToManyField(
                related_name="origins_relations", to="composer.anatomicalentity"
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="anatomical_entities",
            field=models.ManyToManyField(
                blank=True,
                related_name="destination_connection_layers",
                to="composer.anatomicalentity",
            ),
        ),
        migrations.AlterField(
            model_name="synonym",
            name="anatomical_entity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="synonyms",
                to="composer.anatomicalentity",
            ),
        ),
        migrations.AlterField(
            model_name="via",
            name="anatomical_entities",
            field=models.ManyToManyField(
                blank=True,
                related_name="via_connection_layers",
                to="composer.anatomicalentity",
            ),
        ),
    ]
