# Generated by Django 4.1.4 on 2024-07-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0051_alter_anatomicalentity_region_layer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anatomicalentity",
            options={
                "verbose_name": "Anatomical Entity",
                "verbose_name_plural": "Anatomical Entities",
            },
        ),
        migrations.AlterField(
            model_name="connectivitystatement",
            name="projection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IPSI", "ipsilateral"),
                    ("CONTRAT", "contralateral"),
                    ("BI", "bilateral"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
