# Generated by Django 4.1.4 on 2024-07-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0051_alter_anatomicalentity_region_layer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anatomicalentity",
            options={
                "verbose_name": "Anatomical Entity",
                "verbose_name_plural": "Anatomical Entities",
            },
        ),
        migrations.RemoveConstraint(
            model_name="connectivitystatement",
            name="projection_valid",
        ),
    ]
