# Generated by Django 4.1.4 on 2024-07-09 07:09

from django.db import migrations, models
import django.db.models.deletion





class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0052_alter_anatomicalentity_options_and_more"),
    ]

    # Steps taken in migration:
    # 1. create new models for layer and region - NewLayer, NewRegion
    # 2. copy the necessary columns from the old models to the new models - layer_ae_meta, region_ae_meta
    # 3. remove the old models - Layer, Region and it's fk from AnatomicalEntityIntersection
    # 4. rename the new models to the old models - Layer, Region

    operations = [
        migrations.CreateModel(
            name="NewLayer",
            fields=[
                (
                    "layer_id",
                    models.BigAutoField(
                        auto_created=True, 
                        primary_key=True, 
                        serialize=False,
                    ),
                ),
                (
                    "layer_ae_meta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layer_meta",
                        to="composer.anatomicalentitymeta",
                    ),
                )
            ]
        ),
        migrations.RunSQL(
            sql="INSERT INTO composer_newlayer (layer_ae_meta_id) SELECT anatomicalentitymeta_ptr_id FROM composer_layer",
            reverse_sql="",
        ),
        migrations.RemoveField(
            model_name="anatomicalentityintersection",
            name="layer",
        ),
        migrations.DeleteModel(
            name="Layer",
        ),
        migrations.RenameModel(
            old_name="NewLayer",
            new_name="Layer",
        ),


        # ----------------------------
        migrations.CreateModel(
            name="NewRegion",
            fields=[
                (
                    "region_id",
                    models.BigAutoField(
                        auto_created=True, 
                        primary_key=True, 
                        serialize=False,
                    ),
                ),
                (
                    "region_ae_meta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="region_meta",
                        to="composer.anatomicalentitymeta",
                    ),
                )
            ]
        ),
        migrations.RunSQL(
            sql="INSERT INTO composer_newregion (region_ae_meta_id) SELECT anatomicalentitymeta_ptr_id FROM composer_region",
            reverse_sql="",
        ),
        migrations.RemoveField(
            model_name="anatomicalentityintersection",
            name="region",
        ), 
        migrations.DeleteModel(
            name="Region",  
        ),
        migrations.RenameModel(
            old_name="NewRegion",
            new_name="Region",
        ),




    ]
