# Generated by Django 4.1.4 on 2024-07-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0055_auto_20240708_1540"),
    ]

    operations = [
        migrations.RenameField(
            model_name="layer",
            old_name="layer_ae_meta",
            new_name="ae_meta",
        ),
        migrations.RenameField(
            model_name="region",
            old_name="region_ae_meta",
            new_name="ae_meta",
        ),
    ]
