# Generated by Django 4.1.4 on 2024-10-07 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "composer",
            "0060_anatomicalentityintersection_unique_layer_region_combination_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphRenderingState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serialized_graph", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="connectivitystatement",
            constraint=models.CheckConstraint(
                check=models.Q(("projection__in", ["IPSI", "CONTRAT", "BI"])),
                name="projection_valid",
            ),
        ),
        migrations.AddField(
            model_name="graphrenderingstate",
            name="connectivity_statement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_rendering_state",
                to="composer.connectivitystatement",
            ),
        ),
        migrations.AddField(
            model_name="graphrenderingstate",
            name="saved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
