# Generated by Django 4.1.4 on 2024-10-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "composer",
            "0060_anatomicalentityintersection_unique_layer_region_combination_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="connectivitystatement",
            constraint=models.CheckConstraint(
                check=models.Q(("projection__in", ["IPSI", "CONTRAT", "BI"])),
                name="projection_valid",
            ),
        ),
    ]
