# Generated by Django 4.1.4 on 2024-12-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0062_auto_20241122_1333"),
    ]
    operations = [
        migrations.AddField(
            model_name="connectivitystatement",
            name="journey_description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectivitystatement",
            name="journey_entities",
            field=models.JSONField(blank=True, null=True),
        )
    ]
