# Generated by Django 4.1.4 on 2024-11-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0063_alerttype_statementalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerttype",
            name="predicate",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
