# Generated by Django 4.1.4 on 2024-12-08 22:13

from django.db import migrations
from composer.services.graph_service import compile_journey


def update_journey_fields(apps, schema_editor):
    ConnectivityStatement = apps.get_model('composer', 'ConnectivityStatement')
    for cs in ConnectivityStatement.objects.all():
        journey_data = compile_journey(cs)
        cs.journey_description = journey_data['journey']
        cs.journey_entities = journey_data['entities']
        cs.save(update_fields=["journey_description", "journey_entities"])


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0063_connectivitystatement_journey_description_and_more"),
    ]

    operations = [
        migrations.RunPython(update_journey_fields),
    ]
