# Generated by Django 4.1.4 on 2024-12-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0064_alerttype_predicate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementalert",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
