# Generated by Django 4.1.4 on 2024-12-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0065_alter_statementalert_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectivitystatement",
            name="journey_path",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
