# Generated by Django 4.1.4 on 2025-01-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0065_alter_statementalert_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectivitystatement",
            name="curie_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
