# Generated by Django 4.1.4 on 2024-12-18 08:28

from django.db import migrations
from django.db import migrations
from composer.services.graph_service import compile_journey


def update_journey_fields(apps, schema_editor):
    ConnectivityStatement = apps.get_model('composer', 'ConnectivityStatement')
    for cs in ConnectivityStatement.objects.all():
        cs.journey_path = compile_journey(cs)
        cs.save(update_fields=["journey_path"])


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0066_connectivitystatement_journey_path"),
    ]

    operations = [
        migrations.RunPython(update_journey_fields),
    ]
