# Generated by Django 4.1.4 on 2024-12-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0067_auto_20241218_0928"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectivitystatement",
            name="statement_prefix",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectivitystatement",
            name="statement_suffix",
            field=models.TextField(blank=True, null=True),
        ),
    ]
