# Generated by Django 4.1.4 on 2024-12-18 15:59

from composer.services.statement_service import get_prefix_for_statement_preview, get_suffix_for_statement_preview
from django.db import migrations


def update_suffix_prefix_for_connectivity_statement_fields(apps, schema_editor):
    ConnectivityStatement = apps.get_model('composer', 'ConnectivityStatement')
    for cs in ConnectivityStatement.objects.all():
        cs.statement_prefix = get_prefix_for_statement_preview(cs)
        cs.statement_suffix = get_suffix_for_statement_preview(cs)
        cs.save(update_fields=["statement_prefix", "statement_suffix"])


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0068_connectivitystatement_statement_prefix_and_more"),
    ]

    operations = [
        migrations.RunPython(
            update_suffix_prefix_for_connectivity_statement_fields)
    ]
