# Generated by Django 4.1.4 on 2025-02-11 09:12

import composer.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0075_migrate_has_statement_been_exported"),
    ]

    operations = [
        migrations.AlterField(
            model_name="populationset",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[composer.utils.is_valid_population_name],
            ),
        ),
    ]
