# Generated by Django 4.1.4 on 2025-02-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0076_alter_populationset_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="connectivitystatement",
            name="state_valid",
        ),
        migrations.AddConstraint(
            model_name="connectivitystatement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "state__in",
                        [
                            "draft",
                            "compose_now",
                            "in_progress",
                            "to_be_reviewed",
                            "revise",
                            "rejected",
                            "npo_approved",
                            "exported",
                            "deprecated",
                            "invalid",
                        ],
                    )
                ),
                name="state_valid",
            ),
        ),
    ]
