# Generated by Django 4.1.4 on 2025-02-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0077_remove_connectivitystatement_state_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectivitystatement",
            name="compr_uri",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="populationset",
            name="cs_exported_from_this_populationset_incremental_index",
            field=models.IntegerField(default=0),
        ),
    ]
