# Generated by Django 4.1.4 on 2025-02-20 11:37

from django.db import migrations
from composer.enums import CSState

def handle_compr_uri_generation(apps):
    ConnectivityStatement = apps.get_model("composer", "ConnectivityStatement")
    connectivity_statements = ConnectivityStatement.objects.filter(state=CSState.EXPORTED).order_by('id')
    population_index_hashmap = {}
    for connectivity_statement in connectivity_statements:
        COMPR_URI_PREFIX = "https://uri.interlex.org/composer/uris/set/"
        if connectivity_statement.population:
            compr_uri_population_label = connectivity_statement.population.name
        else:
            """All Exported ConnectivityStatements should have a PopulationSet"""
            raise ValueError("PopulationSet is required")
        
        if connectivity_statement.population.id not in population_index_hashmap:
            population_index_hashmap[connectivity_statement.population.id] = 0

        incremental_index = population_index_hashmap[connectivity_statement.population.id] + 1
        population_index_hashmap[connectivity_statement.population.id] = incremental_index
        compr_uri = f"{COMPR_URI_PREFIX}{compr_uri_population_label}/{incremental_index}"
        
        connectivity_statement.compr_uri = compr_uri
        connectivity_statement.save()


def handle_cs_exported_from_this_populationset_incremental(apps):
    PopulationSet = apps.get_model("composer", "PopulationSet")
    for population_set in PopulationSet.objects.all():
        connectivity_statements_count = population_set.connectivitystatement_set.filter(state=CSState.EXPORTED).count()
        population_set.cs_exported_from_this_populationset_incremental_index = connectivity_statements_count
        population_set.save()
    

def add_compr_uri_and_cs_exported_from_this_populationset_incremental_index(apps, schema_editor):
    handle_compr_uri_generation(apps)
    handle_cs_exported_from_this_populationset_incremental(apps)



class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0078_connectivitystatement_compr_uri_and_more"),
    ]

    operations = [
        migrations.RunPython(add_compr_uri_and_cs_exported_from_this_populationset_incremental_index),
    ]
