# Generated by Django 4.1.4 on 2025-04-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0082_alter_sentence_batch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectivitystatement",
            name="short_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
