# Generated by Django 4.1.4 on 2023-04-13 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0001_initial"),
    ]

    def generate_system_user(apps, schema_editor):
        User = apps.get_model('auth', 'User')
        User.objects.create_user(
            username="system",
            email="do_not_remove@system_user.com",
            password=User.objects.make_random_password(),
            first_name="System",
            last_name="User",
            is_staff=True,
        ).save()

    operations = [
        migrations.RunPython(generate_system_user),
    ]
