# Generated by Django 4.1.4 on 2023-04-20 15:00

from django.db import migrations
from django.db.models import F

def update_laterality(apps, schema_editor):
        ConnectivityStatement = apps.get_model('composer', 'ConnectivityStatement')
        ConnectivityStatement.objects.all().update(projection=F("laterality"))
        ConnectivityStatement.objects.filter(projection='ONTRAT').update(projection='CONTRAT')
        ConnectivityStatement.objects.all().update(laterality="UNKNOWN")



class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0004_rename_ansdivision_phenotype_and_more"),
    ]

    operations = [
        migrations.RunPython(update_laterality),
    ]
