# Generated by Django 4.1.4 on 2023-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0009_drop_doi"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectivitystatement",
            name="additional_information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
