# Generated by Django 4.1.4 on 2023-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0010_connectivitystatement_additional_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="phenotype",
            name="ontology_uri",
            field=models.URLField(default=""),
        ),
    ]
