# Generated by Django 4.1.4 on 2023-05-02 14:30

from django.db import migrations

DEFAULT_PHENOTYPES = {
    "enteric": "http://uri.interlex.org/tgbugs/uris/readable/EntericPhenotype",
    "sympathetic post-ganglionic phenotype": "http://uri.interlex.org/tgbugs/uris/readable/neuron-phenotype-sym-post",
    "sympathetic pre-ganglionic phenotype": "http://uri.interlex.org/tgbugs/uris/readable/neuron-phenotype-sym-pre",
    "parasympathetic post-ganglionic phenotype": "http://uri.interlex.org/tgbugs/uris/readable/neuron-phenotype-para-post",
    "parasympathetic pre-ganglionic phenotype": "http://uri.interlex.org/tgbugs/uris/readable/neuron-phenotype-para-pre",
}


def add_default_phenotypes(apps, schema_editor):
    Phenotype = apps.get_model('composer', 'Phenotype')
    for name, ontology_uri in DEFAULT_PHENOTYPES.items():
        phenotype, created = Phenotype.objects.get_or_create(name=name)
        if not created:
            phenotype.ontology_uri = ontology_uri
            phenotype.save()


def remove_default_phenotypes(apps, schema_editor):
    Phenotype = apps.get_model('composer', 'Phenotype')
    for name in DEFAULT_PHENOTYPES.keys():
        Phenotype.objects.filter(name=name).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0011_phenotype_ontology_uri"),
    ]

    operations = [
        migrations.RunPython(add_default_phenotypes, remove_default_phenotypes),
    ]
