# Generated by Django 4.1.4 on 2023-09-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "composer",
            "0020_remove_anatomicalentity_anatomicalentity_upper_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="connectivitystatement",
            name="forward_connection",
            field=models.ManyToManyField(
                blank=True, to="composer.connectivitystatement"
            ),
        ),
    ]
