# Generated by Django 4.1.4 on 2023-10-23 15:32

from django.db import migrations


def migrate_origin_to_origins(apps, schema_editor):
    ConnectivityStatement = apps.get_model('composer', 'ConnectivityStatement')
    for statement in ConnectivityStatement.objects.all():
        if statement.origin:
            statement.origins.add(statement.origin)


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0022_connectivitystatement_origins"),
    ]

    operations = [
        migrations.RunPython(migrate_origin_to_origins),
    ]
