# Generated by Django 4.1.4 on 2023-10-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0026_auto_20231023_1802"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="connectivitystatement",
            name="destination_type_valid",
        ),
        migrations.RemoveField(
            model_name="connectivitystatement",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="connectivitystatement",
            name="destination_type",
        ),
        migrations.AddConstraint(
            model_name="destination",
            constraint=models.CheckConstraint(
                check=models.Q(("type__in", ["AXON-T", "AFFERENT-T", "UNKNOWN"])),
                name="destination_type_valid",
            ),
        ),
    ]
