# Generated by Django 4.1.4 on 2023-10-24 15:39

from django.db import migrations, models


def set_default_order(apps, schema_editor):
    Via = apps.get_model('composer', 'Via')
    default_order = 0
    for via in Via.objects.filter(order__isnull=True):
        via.order = default_order
        via.save()


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0029_auto_20231024_1436"),
    ]

    operations = [
        migrations.RunPython(set_default_order, migrations.RunPython.noop),

        migrations.AlterModelOptions(
            name="via",
            options={"ordering": ["order"], "verbose_name_plural": "Via"},
        ),
        migrations.RemoveField(
            model_name="connectivitystatement",
            name="path",
        ),
        migrations.AddField(
            model_name="via",
            name="from_entities",
            field=models.ManyToManyField(blank=True, to="composer.anatomicalentity"),
        ),
        migrations.AlterField(
            model_name="destination",
            name="anatomical_entities",
            field=models.ManyToManyField(
                blank=True,
                related_name="destination_connection_layers",
                to="composer.anatomicalentity",
            ),
        ),
        migrations.AlterField(
            model_name="via",
            name="anatomical_entities",
            field=models.ManyToManyField(
                blank=True,
                related_name="via_connection_layers",
                to="composer.anatomicalentity",
            ),
        ),
        migrations.AlterField(
            model_name="via",
            name="order",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="via",
            name="type",
            field=models.CharField(
                choices=[("AXON", "Axon"), ("DENDRITE", "Dendrite")],
                default="AXON",
                max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name="via",
            name="anatomical_entity",
        ),
        migrations.RemoveField(
            model_name="via",
            name="display_order",
        ),
    ]
