# Generated by Django 4.1.4 on 2024-01-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0032_alter_connectivitystatement_projection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectivitystatement",
            name="reference_uri",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
