# Generated by Django 4.1.4 on 2024-02-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0034_remove_connectivitystatement_state_valid_and_more"),
    ]

    operations = [
        # ADD the null=True option to the circuit_type, laterality and projection fields
        migrations.AlterField(
            model_name="connectivitystatement",
            name="circuit_type",
            field=models.CharField(
                choices=[
                    ("SENSORY", "Sensory"),
                    ("MOTOR", "Motor"),
                    ("INTRINSIC", "Intrinsic"),
                    ("PROJECTION", "Projection"),
                    ("ANAXONIC", "Anaxonic"),
                    ("UNKNOWN", "Not specified"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="connectivitystatement",
            name="laterality",
            field=models.CharField(
                choices=[
                    ("RIGHT", "Right"),
                    ("LEFT", "Left"),
                    ("UNKNOWN", "Not specified"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="connectivitystatement",
            name="projection",
            field=models.CharField(
                choices=[
                    ("IPSI", "Ipsilateral"),
                    ("CONTRAT", "Contralateral"),
                    ("BI", "Bilateral"),
                    ("UNKNOWN", "Not specified"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
