# Generated by Django 4.1.4 on 2024-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0037_remove_unknown_enum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectivitystatement",
            name="circuit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SENSORY", "Sensory"),
                    ("MOTOR", "Motor"),
                    ("INTRINSIC", "Intrinsic"),
                    ("PROJECTION", "Projection"),
                    ("ANAXONIC", "Anaxonic"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="connectivitystatement",
            name="laterality",
            field=models.CharField(
                blank=True,
                choices=[("RIGHT", "Right"), ("LEFT", "Left")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="connectivitystatement",
            name="projection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IPSI", "Ipsilateral"),
                    ("CONTRAT", "Contralateral"),
                    ("BI", "Bilateral"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
