# Generated by Django 4.1.4 on 2024-02-13 13:01

from django.db import migrations, models


def migrate_deprecated_states(apps, schema_editor):
    Sentence = apps.get_model('composer', 'Sentence')
    ConnectivityStatement = apps.get_model('composer', 'ConnectivityStatement')

    Sentence.objects.filter(state='duplicate').update(state='excluded')

    Sentence.objects.filter(state='to_be_reviewed').update(state='needs_further_review')

    ConnectivityStatement.objects.filter(state='curated').update(state='in_progress')

    ConnectivityStatement.objects.filter(state__in=['excluded', 'connection_missing']).update(state='rejected')


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0039_remove_connectivitystatement_state_valid_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_deprecated_states),

        migrations.AddConstraint(
            model_name="connectivitystatement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "state__in",
                        [
                            "draft",
                            "compose_now",
                            "in_progress",
                            "to_be_reviewed",
                            "revise",
                            "rejected",
                            "npo_approved",
                            "exported",
                            "invalid",
                        ],
                    )
                ),
                name="state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sentence",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "state__in",
                        [
                            "open",
                            "needs_further_review",
                            "compose_later",
                            "ready_to_compose",
                            "compose_now",
                            "completed",
                            "excluded",
                        ],
                    )
                ),
                name="sentence_state_valid",
            ),
        ),
    ]
