# Generated by Django 4.1.4 on 2024-03-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0042_auto_20240313_1718"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anatomicalentity",
            name="ontology_uri",
            field=models.URLField(unique=True),
        ),
    ]
