# Generated by Django 4.1.4 on 2024-03-13 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0043_alter_anatomicalentity_ontology_uri"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="anatomicalentity",
            name="ae_unique_upper_name",
        ),
    ]
