# Generated by Django 4.1.4 on 2024-03-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0045_alter_synonym_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnatomicalEntityIntersection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnatomicalEntityMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("ontology_uri", models.URLField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Anatomical Entities Meta",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="synonym",
            name="anatomical_entity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="synonyms",
                to="composer.anatomicalentity",
            ),
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "anatomicalentitymeta_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="composer.anatomicalentitymeta",
                    ),
                ),
            ],
            bases=("composer.anatomicalentitymeta",),
        ),
        migrations.CreateModel(
            name="AnatomicalEntityNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region_layer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composer.anatomicalentityintersection",
                    ),
                ),
                (
                    "simple_entity",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composer.anatomicalentitymeta",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="connectivitystatement",
            name="origins_new",
            field=models.ManyToManyField(
                related_name="origins_relations_new", to="composer.anatomicalentitynew"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="anatomical_entities_new",
            field=models.ManyToManyField(
                blank=True,
                related_name="destination_connection_layers_new",
                to="composer.anatomicalentitynew",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="from_entities_new",
            field=models.ManyToManyField(blank=True, to="composer.anatomicalentitynew"),
        ),
        migrations.AddField(
            model_name="synonym",
            name="anatomical_entity_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="synonyms_new",
                to="composer.anatomicalentitynew",
            ),
        ),
        migrations.AddField(
            model_name="via",
            name="anatomical_entities_new",
            field=models.ManyToManyField(
                blank=True,
                related_name="via_connection_layers",
                to="composer.anatomicalentitynew",
            ),
        ),
        migrations.AddField(
            model_name="via",
            name="from_entities_new",
            field=models.ManyToManyField(blank=True, to="composer.anatomicalentitynew"),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "anatomicalentitymeta_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="composer.anatomicalentitymeta",
                    ),
                ),
                (
                    "layers",
                    models.ManyToManyField(
                        through="composer.AnatomicalEntityIntersection",
                        to="composer.layer",
                    ),
                ),
            ],
            bases=("composer.anatomicalentitymeta",),
        ),
        migrations.AddField(
            model_name="anatomicalentityintersection",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="composer.layer"
            ),
        ),
        migrations.AddField(
            model_name="anatomicalentityintersection",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="composer.region"
            ),
        ),
    ]
