# Generated by Django 4.1.4 on 2024-03-20 13:40

from django.db import migrations


def copy_anatomical_entities_to_new(apps, schema_editor):
    AnatomicalEntity = apps.get_model('composer', 'AnatomicalEntity')
    AnatomicalEntityNew = apps.get_model('composer', 'AnatomicalEntityNew')
    AnatomicalEntityMeta = apps.get_model('composer', 'AnatomicalEntityMeta')
    Destination = apps.get_model('composer', 'Destination')
    Via = apps.get_model('composer', 'Via')
    ConnectivityStatement = apps.get_model('composer', 'ConnectivityStatement')
    Synonym = apps.get_model('composer', 'Synonym')

    # Copy AnatomicalEntity instances to AnatomicalEntityNew
    for entity in AnatomicalEntity.objects.all():
        new_entity_meta = AnatomicalEntityMeta.objects.create(
            name=entity.name,
            ontology_uri=entity.ontology_uri,
        )

        new_entity = AnatomicalEntityNew.objects.create(simple_entity=new_entity_meta)

        # Update ManyToMany relationships for Destination
        for destination in Destination.objects.filter(anatomical_entities=entity):
            destination.anatomical_entities_new.add(new_entity)

        for destination in Destination.objects.filter(from_entities=entity):
            destination.from_entities_new.add(new_entity)

        # Update ManyToMany relationships for Via
        for via in Via.objects.filter(anatomical_entities=entity):
            via.anatomical_entities_new.add(new_entity)

        for via in Via.objects.filter(from_entities=entity):
            via.from_entities_new.add(new_entity)

        # Update ManyToMany relationships for ConnectivityStatement origins
        for cs in ConnectivityStatement.objects.filter(origins=entity):
            cs.origins_new.add(new_entity)

        Synonym.objects.filter(anatomical_entity=entity).update(
            anatomical_entity_new=new_entity
        )


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0046_anatomicalentityintersection_anatomicalentitymeta_and_more"),
    ]

    operations = [migrations.RunPython(copy_anatomical_entities_to_new), ]
