# Generated by Django 4.1.4 on 2024-03-21 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0049_rename_anatomicalentitynew_anatomicalentity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anatomicalentityintersection",
            options={
                "verbose_name": "Region/Layer Combination",
                "verbose_name_plural": "Region/Layer Combinations",
            },
        ),
        migrations.AlterModelOptions(
            name="anatomicalentitymeta",
            options={
                "ordering": ["name"],
                "verbose_name": "Anatomical Entity",
                "verbose_name_plural": "Anatomical Entities",
            },
        ),
        migrations.AlterField(
            model_name="anatomicalentity",
            name="region_layer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="composer.anatomicalentityintersection",
            ),
        ),
        migrations.AlterField(
            model_name="connectivitystatement",
            name="origins",
            field=models.ManyToManyField(
                related_name="origins_relations", to="composer.anatomicalentity"
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="anatomical_entities",
            field=models.ManyToManyField(
                blank=True,
                related_name="destination_connection_layers",
                to="composer.anatomicalentity",
            ),
        ),
        migrations.AlterField(
            model_name="synonym",
            name="anatomical_entity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="synonyms",
                to="composer.anatomicalentity",
            ),
        ),
        migrations.AddConstraint(
            model_name="anatomicalentity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("region_layer__isnull", True), ("simple_entity__isnull", False)
                    ),
                    models.Q(
                        ("region_layer__isnull", False), ("simple_entity__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="check_anatomical_entity_exclusivity",
            ),
        ),
    ]
