# Generated by Django 4.1.4 on 2024-04-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0050_alter_anatomicalentityintersection_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anatomicalentity",
            name="region_layer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="composer.anatomicalentityintersection",
            ),
        ),
    ]
