# Generated by Django 4.1.4 on 2025-01-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0068_auto_20250120_1335"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectivitystatement",
            name="statement_prefix",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectivitystatement",
            name="statement_suffix",
            field=models.TextField(blank=True, null=True),
        ),
    ]
