# Generated by Django 4.1.4 on 2025-01-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0071_remove_via_via_type_valid_alter_via_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerttype",
            name="uri",
            field=models.URLField(unique=True),
        ),
    ]
