# Generated by Django 4.1.4 on 2025-02-04 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0072_alter_alerttype_uri"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Population Sets",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="connectivitystatement",
            name="population",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="composer.populationset",
                verbose_name="Population Set",
            ),
        ),
    ]
