# Generated by Django 4.1.4 on 2025-02-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0073_populationset_connectivitystatement_population"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectivitystatement",
            name="has_statement_been_exported",
            field=models.BooleanField(default=False),
        ),
    ]
