# Generated by Django 4.2.19 on 2025-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0081_auto_20250227_2147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentence",
            name="batch_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
