# Generated by Django 4.2.19 on 2025-05-22 21:33

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0083_add_curie_id_generation_for_composer_statements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectivitystatement",
            name="state",
            field=django_fsm.FSMField(
                db_index=True, default="draft", max_length=50, protected=True
            ),
        ),
    ]
