# Generated by Django 4.2.19 on 2025-05-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0084_alter_connectivitystatement_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("predicate_name", models.CharField(max_length=255)),
                ("predicate_uri", models.URLField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single", "Single select"),
                            ("multi", "Multi select"),
                            ("text", "Text area"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Triple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("uri", models.URLField()),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triples",
                        to="composer.relationship",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConnectivityStatementTriple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("free_text", models.TextField(blank=True, null=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composer.relationship",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_triples",
                        to="composer.connectivitystatement",
                    ),
                ),
                (
                    "triple",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="composer.triple",
                    ),
                ),
            ],
            options={
                "unique_together": {("statement", "relationship", "triple")},
            },
        ),
    ]
