# Generated by Django 4.2.19 on 2025-06-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0085_relationship_triple_connectivitystatementtriple"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connectivitystatementtriple",
            old_name="statement",
            new_name="connectivity_statement",
        ),
        migrations.AlterUniqueTogether(
            name="connectivitystatementtriple",
            unique_together={("connectivity_statement", "relationship", "triple")},
        ),
    ]
