# Generated by Django 4.1.13 on 2025-06-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "composer",
            "0086_rename_statement_connectivitystatementtriple_connectivity_statement_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="connectivitystatementtriple",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="statementalert",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="synonym",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="connectivitystatementtriple",
            constraint=models.UniqueConstraint(
                fields=("connectivity_statement", "relationship", "triple"),
                name="unique_statement_relationship_triple",
            ),
        ),
        migrations.AddConstraint(
            model_name="statementalert",
            constraint=models.UniqueConstraint(
                fields=("connectivity_statement", "alert_type"),
                name="unique_statement_alert_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="synonym",
            constraint=models.UniqueConstraint(
                fields=("anatomical_entity", "name"), name="unique_synonym_per_entity"
            ),
        ),
    ]
