# Generated by Django 4.1.13 on 2025-06-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0087_alter_connectivitystatementtriple_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="triple",
            constraint=models.UniqueConstraint(
                fields=("name", "uri", "relationship"),
                name="unique_triple_per_relationship",
            ),
        ),
    ]
