# Generated by Django 4.1.13 on 2025-06-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0088_triple_unique_triple_per_relationship"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.UniqueConstraint(
                fields=("title", "predicate_name", "predicate_uri"),
                name="unique_relationship",
            ),
        ),
    ]
