# Generated by Django 4.1.13 on 2025-09-24 15:17

import composer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0089_relationship_unique_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provenance",
            name="uri",
            field=composer.models.ProvenanceUriField(
                max_length=500,
                validators=[
                    composer.models.validate_provenance_uri,
                ],
            ),
        ),
    ]
