# Generated by Django 4.2.25 on 2025-10-06 21:11

import composer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0090_alter_provenance_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentence",
            name="external_ref",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="pmcid",
            field=composer.models.PmcIdField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
