# Generated by Django 4.1.13 on 2025-10-10 14:13

import composer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0091_alter_sentence_external_ref_alter_sentence_pmcid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertConsultant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uri",
                    composer.models.UriField(
                        max_length=500,
                        validators=[
                            composer.models.validate_uri,
                        ],
                    ),
                ),
                (
                    "connectivity_statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composer.connectivitystatement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expert Consultants",
            },
        ),
    ]
