# Generated by Django 4.1.13 on 2025-10-10 18:31

import composer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0092_expertconsultant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertconsultant",
            name="uri",
            field=composer.models.UriField(max_length=500),
        ),
        migrations.AlterField(
            model_name="provenance",
            name="uri",
            field=composer.models.UriField(max_length=500),
        ),
    ]
