# Generated by Django 4.1.13 on 2025-10-13 11:53

from django.db import migrations, models


def migrate_relationship_types_forward(apps, schema_editor):
    """
    Migrate old relationship type values to new naming convention:
    - 'single' -> 'triple_single'
    - 'multi' -> 'triple_multi'
    """
    Relationship = apps.get_model("composer", "Relationship")
    
    # Update single to triple_single
    Relationship.objects.filter(type="single").update(type="triple_single")
    
    # Update multi to triple_multi
    Relationship.objects.filter(type="multi").update(type="triple_multi")


def migrate_relationship_types_backward(apps, schema_editor):
    """
    Reverse migration: revert to old naming convention:
    - 'triple_single' -> 'single'
    - 'triple_multi' -> 'multi'
    """
    Relationship = apps.get_model("composer", "Relationship")
    
    # Revert triple_single to single
    Relationship.objects.filter(type="triple_single").update(type="single")
    
    # Revert triple_multi to multi
    Relationship.objects.filter(type="triple_multi").update(type="multi")


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0094_alter_connectivitystatementtriple_options_and_more"),
    ]

    operations = [
        # Step 1: Temporarily allow both old and new values
        migrations.AlterField(
            model_name="relationship",
            name="type",
            field=models.CharField(
                choices=[
                    ("single", "Single select (deprecated)"),
                    ("multi", "Multi select (deprecated)"),
                    ("triple_single", "Triple - Single select"),
                    ("triple_multi", "Triple - Multi select"),
                    ("anatomical_single", "Anatomical Entity - Single select"),
                    ("anatomical_multi", "Anatomical Entity - Multi select"),
                    ("text", "Text area"),
                ],
                max_length=20,
            ),
        ),
        
        # Step 2: Migrate the data
        migrations.RunPython(
            migrate_relationship_types_forward,
            migrate_relationship_types_backward,
        ),
        
        # Step 3: Remove deprecated choices and finalize
        migrations.AlterField(
            model_name="relationship",
            name="type",
            field=models.CharField(
                choices=[
                    ("triple_single", "Triple - Single select"),
                    ("triple_multi", "Triple - Multi select"),
                    ("anatomical_single", "Anatomical Entity - Single select"),
                    ("anatomical_multi", "Anatomical Entity - Multi select"),
                    ("text", "Text area"),
                ],
                max_length=20,
            ),
        ),
    ]
