# Generated by Django 4.1.13 on 2025-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "composer",
            "0096_remove_connectivitystatementtriple_unique_statement_relationship_triple_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="relationship",
            name="custom_ingestion_code",
            field=models.TextField(
                blank=True,
                help_text="Optional Python code to extract data from NeuroDM for this relationship during ingestion. The code has access to:\n- 'fc': dict with neuron properties (id, label, species, phenotype, etc.)\n- 'fc[\"_neuron\"]': the NeuroDM neuron object with core_graph for RDF queries\n\nYou can import any packages available in the base image (e.g., from pyontutils.namespaces import ilxtr)\n\nExample - Query neuron RDF graph:\n  from pyontutils.namespaces import ilxtr\n  neuron = fc['_neuron']\n  values = [str(o) for s, p, o in neuron.core_graph[neuron.identifier:ilxtr.hasPhenotype]]\n\nThe code must define a 'result' variable with the output:\n- For TRIPLE relationships: list of dicts [{'name': str, 'uri': str}, ...]\n- For TEXT relationships: list of strings or single string\n- For ANATOMICAL_ENTITY relationships: list of URIs (strings)\n\nErrors are logged to the ingestion anomalies file and the relationship will be skipped.",
                null=True,
            ),
        ),
    ]
