# Generated by Django 4.1.13 on 2025-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "composer",
            "0096_remove_connectivitystatementtriple_unique_statement_relationship_triple_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="relationship",
            name="custom_ingestion_code",
            field=models.TextField(
                blank=True,
                null=True,
            ),
        ),
    ]
