# Generated by Django on 2025-03-04

from django.db import migrations


def convert_reference_uri_https_to_http(apps, schema_editor):
    """
    Converts all reference_uri values from https to http.
    """
    ConnectivityStatement = apps.get_model("composer", "ConnectivityStatement")
    
    # Get all statements with reference_uri starting with https://
    statements_with_https = ConnectivityStatement.objects.filter(
        reference_uri__startswith="https://uri.interlex.org/composer/uris/set/"
    )
    
    # Update each statement to use http instead of https
    for statement in statements_with_https:
        statement.reference_uri = statement.reference_uri.replace("https://", "http://", 1)
        statement.save(update_fields=["reference_uri"])


def reverse_convert_reference_uri_http_to_https(apps, schema_editor):
    """
    Reverse migration: Converts reference_uri values back from http to https.
    """
    ConnectivityStatement = apps.get_model("composer", "ConnectivityStatement")
    
    # Get all statements with reference_uri starting with http://
    statements_with_http = ConnectivityStatement.objects.filter(
        reference_uri__startswith="http://uri.interlex.org/composer/uris/set/"
    )
    
    # Update each statement to use https instead of http
    for statement in statements_with_http:
        statement.reference_uri = statement.reference_uri.replace("http://", "https://", 1)
        statement.save(update_fields=["reference_uri"])


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0097_relationship_custom_ingestion_code"),
    ]

    operations = [
        migrations.RunPython(
            convert_reference_uri_https_to_http,
            reverse_code=reverse_convert_reference_uri_http_to_https
        ),
    ]
